const id = (name = "id") => ({ name, in: "path", required: true, schema: { type: "string", pattern: "^[0-9]+$" } });
const periodKey = { name: "periodKey", in: "path", required: true, description: "Input Period key inherited from KPI Pool", schema: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$", example: "2026-08" } };
const json = (schema: object) => ({ required: true, content: { "application/json": { schema } } });
const response = (description: string, schema?: object) => ({ description, ...(schema ? { content: { "application/json": { schema } } } : {}) });
const dataEnvelope = (schema: object) => ({ type: "object", required: ["data"], properties: { data: schema } });
const errorResponses = { "404": response("Scorecard or period resource not found"), "409": response("Lifecycle, finalized-state, or Pool Composition conflict"), "422": response("Domain validation failed"), "503": response("Stable Pool contract exists but its local Scorecards projection is unavailable") };

export const openApiDocument = {
  openapi: "3.0.3",
  info: { title: "EXA Scorecards Service", version: "0.1.0", description: "Scorecard identity, organizational scope, and per-Input-Period KPI selection, links, weights, and finalization." },
  servers: [{ url: "http://localhost:4003" }],
  paths: {
    "/api/health/live": { get: { summary: "Liveness probe", responses: { "200": response("Process is alive") } } },
    "/api/health/ready": { get: { summary: "Readiness probe", responses: { "200": response("MySQL available and NATS state reported"), "503": response("Dependency unavailable") } } },
    "/api/v1/scorecards/eligible-pools": { get: { summary: "List real ACTIVE KPI Pools", responses: { "200": response("Eligible Pools with inherited schedule", dataEnvelope({ type: "array", items: { $ref: "#/components/schemas/EligiblePool" } })), "503": response("KPI Pool Service unavailable") } } },
    "/api/v1/scorecards": {
      get: { summary: "List Scorecards with database pagination", parameters: [
        { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } }, { name: "pageSize", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 10 } },
        { name: "search", in: "query", schema: { type: "string" } }, { name: "status", in: "query", schema: { type: "array", items: { enum: ["DRAFT", "ACTIVE", "INACTIVE"] } }, style: "form", explode: true },
        { name: "department", in: "query", schema: { type: "array", items: { type: "string" } }, style: "form", explode: true }, { name: "frequency", in: "query", schema: { type: "array", items: { type: "string" } }, style: "form", explode: true },
        { name: "year", in: "query", schema: { type: "array", items: { type: "integer" } }, style: "form", explode: true }, { name: "sortBy", in: "query", schema: { enum: ["scorecardCode", "scorecardName", "statusCode", "createdAt", "updatedAt"] } }, { name: "sortOrder", in: "query", schema: { enum: ["asc", "desc"] } },
      ], responses: { "200": response("Paginated Scorecards", { $ref: "#/components/schemas/ScorecardPage" }) } },
      post: { summary: "Create DRAFT Scorecard Information", requestBody: json({ $ref: "#/components/schemas/CreateScorecard" }), responses: { "201": response("Scorecard created", dataEnvelope({ $ref: "#/components/schemas/Scorecard" })), "422": response("Pool or organizational scope is not eligible") } },
    },
    "/api/v1/scorecards/{id}": { parameters: [id()], get: { summary: "Get Scorecard Information", responses: { "200": response("Scorecard detail", dataEnvelope({ $ref: "#/components/schemas/Scorecard" })), "404": response("Not found") } }, patch: { summary: "Update allowed Scorecard Information and assignments", requestBody: json({ $ref: "#/components/schemas/UpdateScorecard" }), responses: { "200": response("Scorecard updated", dataEnvelope({ $ref: "#/components/schemas/Scorecard" })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/deactivate": { parameters: [id()], patch: { summary: "Deactivate without deleting history", responses: { "200": response("Scorecard deactivated", dataEnvelope({ $ref: "#/components/schemas/Scorecard" })), "409": response("Invalid lifecycle transition") } } },
    "/api/v1/scorecards/pool-workflow": { get: { summary: "Get real Scorecard workflow summary for Pool Period Schedule", parameters: [{ name: "poolId", in: "query", required: true, schema: { type: "string", pattern: "^[0-9]+$" } }, { ...periodKey, in: "query" }], responses: { "200": response("Scorecard Composition counts", dataEnvelope({ $ref: "#/components/schemas/PoolWorkflow" })) } } },
    "/api/v1/scorecards/pool-workflow/batch": { post: { summary: "Count Scorecards using KPIs for multiple Pool Input Periods", description: "Returns period-scoped usage counts in one request for KPI Pool Overview.", requestBody: json({ type: "object", required: ["targets"], properties: { targets: { type: "array", minItems: 1, maxItems: 100, items: { type: "object", required: ["poolId", "periodKey"], properties: { poolId: { type: "string", pattern: "^[0-9]+$" }, periodKey: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" } } } } } }), responses: { "200": response("Period-scoped Scorecard usage counts", dataEnvelope({ type: "array", items: { type: "object", properties: { poolId: { type: "string" }, periodKey: { type: "string" }, scorecardsUsing: { type: "integer" } } } })), "422": response("Invalid target list") } } },
    "/api/v1/scorecards/{id}/periods": { parameters: [id()], get: { summary: "List Input Periods inherited from KPI Pool", responses: { "200": response("Temporal availability", dataEnvelope({ type: "array", items: { $ref: "#/components/schemas/ScorecardPeriod" } })), "404": response("Scorecard not found") } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/composition": { parameters: [id(), periodKey], get: { summary: "Get exact temporal Scorecard Composition", responses: { "200": response("Composition", dataEnvelope({ $ref: "#/components/schemas/Composition" })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/available-kpis": { parameters: [id(), periodKey], get: { summary: "List KPIs from the exact FINALIZED Pool Composition", responses: { "200": response("Eligible Pool memberships", dataEnvelope({ type: "array", items: { $ref: "#/components/schemas/AvailableKpi" } })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/kpis": { parameters: [id(), periodKey], post: { summary: "Add KPI memberships to this Scorecard period", requestBody: json({ type: "object", required: ["items"], properties: { items: { type: "array", minItems: 1, items: { type: "object", required: ["poolMembershipExternalId", "weight"], properties: { poolMembershipExternalId: { type: "string" }, weight: { type: "number", minimum: 0, maximum: 100 } } } } } }), responses: { "201": response("Composition updated", dataEnvelope({ $ref: "#/components/schemas/Composition" })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/kpis/{configurationId}": { parameters: [id(), periodKey, id("configurationId")], delete: { summary: "Unlink KPI from this Scorecard period only", responses: { "204": response("Unlinked"), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/weights": { parameters: [id(), periodKey], patch: { summary: "Persist temporal KPI and linked Scorecard weights", requestBody: json({ $ref: "#/components/schemas/Weights" }), responses: { "200": response("Composition updated", dataEnvelope({ $ref: "#/components/schemas/Composition" })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/linked-scorecards": { parameters: [id(), periodKey], get: { summary: "List eligible temporal linked Scorecards", responses: { "200": response("Eligible Scorecards", dataEnvelope({ type: "array", items: { type: "object" } })), ...errorResponses } }, post: { summary: "Link a Scorecard for this Input Period", requestBody: json({ type: "object", required: ["linkedScorecardId", "weight"], properties: { linkedScorecardId: { type: "string" }, weight: { type: "number", minimum: 0, maximum: 100 } } }), responses: { "201": response("Link persisted", dataEnvelope({ $ref: "#/components/schemas/Composition" })), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/linked-scorecards/{linkedScorecardId}": { parameters: [id(), periodKey, id("linkedScorecardId")], delete: { summary: "Unlink Scorecard from this Input Period only", responses: { "204": response("Unlinked"), ...errorResponses } } },
    "/api/v1/scorecards/{id}/periods/{periodKey}/finalize": { parameters: [id(), periodKey], post: { summary: "Finalize transactionally", description: "Requires exact FINALIZED Pool Composition membership, no cycles, eligible same-period links, and Decimal total 100.0000. First finalization activates the Scorecard and both facts use Outbox.", responses: { "200": response("Finalized composition", dataEnvelope({ $ref: "#/components/schemas/Composition" })), ...errorResponses } } },
  },
  components: { schemas: {
    EligiblePool: { type: "object", properties: { id: { type: "string" }, poolCode: { type: "string" }, poolName: { type: "string" }, validFrom: { type: "string", format: "date" }, validTo: { type: "string", format: "date" }, inputPeriods: { type: "integer" } } },
    Scorecard: { type: "object", properties: { id: { type: "string" }, code: { type: "string" }, name: { type: "string" }, status: { enum: ["DRAFT", "ACTIVE", "INACTIVE"] }, kpiPool: { type: "object" }, poolSchedule: { type: "object", nullable: true }, companies: { type: "array", items: { type: "object" } }, departments: { type: "array", items: { type: "object" } } } },
    ScorecardPage: { allOf: [dataEnvelope({ type: "array", items: { $ref: "#/components/schemas/Scorecard" } }), { type: "object", properties: { meta: { type: "object", properties: { page: { type: "integer" }, pageSize: { type: "integer" }, totalItems: { type: "integer" }, totalPages: { type: "integer" } } } } }] },
    CreateScorecard: { type: "object", required: ["name", "kpiPoolExternalId", "departments"], properties: { name: { type: "string" }, description: { type: "string", nullable: true }, kpiPoolExternalId: { type: "string" }, departments: { type: "array", minItems: 1, items: { type: "object" } }, collaborators: { type: "array", items: { type: "object" } } } }, UpdateScorecard: { type: "object", properties: { name: { type: "string" }, description: { type: "string", nullable: true }, departments: { type: "array", items: { type: "object" } }, collaborators: { type: "array", items: { type: "object" } } } },
    ScorecardPeriod: { type: "object", properties: { periodKey: { type: "string", pattern: "^\\d{4}-\\d{2}$" }, poolPeriodId: { type: "string", nullable: true }, poolCompositionId: { type: "string", nullable: true }, scorecardCompositionId: { type: "string", nullable: true }, scorecardCompositionStatus: { enum: ["AVAILABLE", "UNAVAILABLE", "PREPARING", "FINALIZED"] } } },
    Composition: { type: "object", properties: { id: { type: "string" }, periodKey: { type: "string" }, status: { enum: ["PREPARING", "FINALIZED"] }, poolPeriodExternalId: { type: "string", nullable: true }, poolCompositionExternalId: { type: "string", nullable: true }, kpis: { type: "array", items: { type: "object" } }, linkedScorecards: { type: "array", items: { type: "object" } }, weights: { type: "object", properties: { kpis: { type: "string", example: "70.0000" }, linkedScorecards: { type: "string", example: "30.0000" }, total: { type: "string", example: "100.0000" } } } } },
    AvailableKpi: { type: "object", properties: { poolMembershipExternalId: { type: "string" }, kpiDefinitionExternalId: { type: "string" }, kpiConfigurationExternalId: { type: "string" }, selectionStatus: { enum: ["AVAILABLE_TO_SELECT", "SELECTED_IN_SCORECARD"] } } },
    Weights: { type: "object", required: ["kpis", "linkedScorecards"], properties: { kpis: { type: "array", items: { type: "object", properties: { kpiConfigurationExternalId: { type: "string" }, weight: { type: "number" } } } }, linkedScorecards: { type: "array", items: { type: "object", properties: { linkedScorecardId: { type: "string" }, weight: { type: "number" } } } } } },
    PoolWorkflow: { type: "object", properties: { poolId: { type: "string" }, periodKey: { type: "string" }, totalScorecards: { type: "integer" }, preparing: { type: "integer" }, finalized: { type: "integer" }, pending: { type: "integer" }, status: { enum: ["NOT_STARTED", "IN_PROGRESS", "FINALIZED"] } } },
  } },
} as const;
