import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Building2, CalendarDays, CalendarRange, Eye, Layers3, Link2, Search, Target, UsersRound } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { scorecardService } from "./scorecard.service";
import "./scorecards.css";

const formatPeriod = (value: string) => { const [year, month] = value.split("-").map(Number); return year && month ? `${new Intl.DateTimeFormat("en", { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1)))} • ${year}` : value; };
const formatMonth = (value: string) => new Intl.DateTimeFormat("en", { month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value));

export function ScorecardDetail() {
  const [params] = useSearchParams();
  const id = Number(params.get("scorecardId") ?? 0);
  const [periodKey, setPeriodKey] = useState("");
  const [search, setSearch] = useState("");
  const scorecard = useQuery({ queryKey: ["scorecard", id], queryFn: () => scorecardService.getById(id), enabled: id > 0 });
  const periods = useQuery({ queryKey: ["scorecard-periods", id], queryFn: () => scorecardService.periods(id), enabled: id > 0 });
  useEffect(() => { if (!periodKey && periods.data?.length) setPeriodKey(periods.data.find((row) => row.scorecardCompositionStatus !== "UNAVAILABLE")?.periodKey ?? periods.data[0].periodKey); }, [periodKey, periods.data]);
  const period = periods.data?.find((row) => row.periodKey === periodKey);
  const composition = useQuery({ queryKey: ["scorecard-composition", id, periodKey], queryFn: () => scorecardService.composition(id, periodKey), enabled: id > 0 && Boolean(periodKey) && period?.scorecardCompositionStatus !== "UNAVAILABLE", retry: false });
  const query = search.trim().toLowerCase();
  const filteredKpis = useMemo(() => (composition.data?.kpis ?? []).filter((row) => `${row.configurationCode} ${row.definitionCode} ${row.definitionName} ${row.categoryName ?? ""} ${row.dataSource ?? ""}`.toLowerCase().includes(query)), [composition.data?.kpis, query]);
  const filteredLinks = useMemo(() => (composition.data?.linkedScorecards ?? []).filter((row) => `${row.code} ${row.name} ${row.companies.join(" ")} ${row.departments.join(" ")}`.toLowerCase().includes(query)), [composition.data?.linkedScorecards, query]);

  if (scorecard.isLoading) return <main className="scorecard-page scorecard-detail-page"><div className="scorecard-detail-loading">Loading Scorecard...</div></main>;
  if (scorecard.isError || periods.isError) return <main className="scorecard-page scorecard-detail-page"><section className="scorecard-detail-error"><h1>Scorecard details could not be loaded</h1><p>{((scorecard.error ?? periods.error) as Error).message}</p><Link className="primary-button" to="/app/scorecards/overview">Back to Scorecard Overview</Link></section></main>;
  if (!scorecard.data) return <main className="scorecard-page scorecard-detail-page"><h1>Scorecard not found</h1></main>;

  const item = scorecard.data;
  const kpis = composition.data?.kpis ?? [];
  const links = composition.data?.linkedScorecards ?? [];
  const kpiWeight = Number(composition.data?.weights.kpis ?? 0);
  const linkedWeight = Number(composition.data?.weights.linkedScorecards ?? 0);
  const totalWeight = Number(composition.data?.weights.total ?? 0);
  const status = composition.data?.status ?? period?.scorecardCompositionStatus ?? "UNAVAILABLE";
  const schedule = item.poolSchedule ? `${formatMonth(item.poolSchedule.validFrom)} – ${formatMonth(item.poolSchedule.validTo)} · ${item.poolSchedule.frequency}` : "Schedule unavailable";

  return <main className="scorecard-page scorecard-detail-page">
    <nav className="kpi-breadcrumb"><Link to="/app/scorecards/overview">ScoreCards</Link><span>/</span><span>Scorecard Detail</span></nav>
    <header className="scorecard-detail-hero"><div><div className="scorecard-detail-title-line"><span className="code-pill">{item.code}</span><span className={`scorecard-status ${item.status.toLowerCase()}`}><i/>{item.status}</span></div><h1>{item.name}</h1><p>Scorecard identity, scope and period composition.</p></div><Link className="button scorecard-edit-assignment" to={`/app/scorecards/assignment?scorecardId=${id}&period=${encodeURIComponent(periodKey)}`}>Edit Assignment</Link></header>
    <section className="scorecard-detail-info"><header><div><Layers3 size={18}/><span><strong>Scorecard Header</strong><small>General information and selected Input Period.</small></span></div><span className="read-only-badge">Detail View</span></header><div className="scorecard-detail-info-grid">
      <Fact icon={<Target size={17}/>} label="Scorecard Name" value={item.name} extra={item.code}/><Fact icon={<Building2 size={17}/>} label="Companies" value={item.company || "Not available"}/><Fact icon={<Target size={17}/>} label="KPI Pool Source" value={item.poolSource}/><Fact icon={<CalendarRange size={17}/>} label="Pool Schedule" value={schedule}/><Fact icon={<UsersRound size={17}/>} label="Scope" value={`${item.departments.length} Departments · ${item.collaborators} Collaborators`} extra={item.departments.join(", ") || "No departments"}/>
      <article className="scorecard-detail-fact"><span><CalendarDays size={17}/></span><div><small>Input Period</small><select className="scorecard-detail-period-select" value={periodKey} onChange={(event) => { setPeriodKey(event.target.value); setSearch(""); }}>{periods.data?.map((row) => <option value={row.periodKey} key={row.periodKey}>{formatPeriod(row.periodKey)} · {row.scorecardCompositionStatus.replace(/_/g, " ")}</option>)}</select></div></article>
    </div></section>
    {period?.scorecardCompositionStatus === "UNAVAILABLE" ? <section className="scorecard-empty-state"><CalendarDays size={28}/><h2>Composition unavailable</h2><p>The source Pool Composition has not been finalized for this Input Period.</p></section> : <>
      <div className="scorecard-composition-overview"><section className="scorecard-composition-card"><header><div><h2>Scorecard Summary</h2><p>{formatPeriod(periodKey)} composition.</p></div><strong>{status}</strong></header><div className="scorecard-composition-chart"><div className="scorecard-donut" style={{ background: totalWeight ? `conic-gradient(#2f68df 0 ${kpiWeight / totalWeight * 100}%,#13ae78 ${kpiWeight / totalWeight * 100}% 100%)` : "var(--ems-surface-muted)" }}><span><strong>{totalWeight}%</strong><small>Total Composition</small></span></div><div className="scorecard-composition-totals"><div><i className="composition-dot"/><span><small>KPIs Included</small><strong>{kpis.length} · {kpiWeight}%</strong></span></div><div><i className="composition-dot linked"/><span><small>Linked Scorecards</small><strong>{links.length} · {linkedWeight}%</strong></span></div></div></div></section>
        <section className="scorecard-breakdown-card"><header><div><h2>Composition Breakdown</h2><p>Weight distribution for the selected Input Period.</p></div></header><div className="scorecard-breakdown-list"><div className="primary"><span>KPI</span><div><strong>KPI Performance</strong><small>{kpis.length} KPI Configurations selected from the Pool</small></div><b>{kpiWeight}%</b></div>{links.map((row, index) => <div key={row.id}><span>{index + 1}</span><div><strong>{row.code} · {row.name}</strong><small>{row.departments.join(", ") || "Linked Scorecard"}</small></div><b>{Number(row.weight)}%</b></div>)}{!links.length && <div><span>—</span><div><strong>No Linked Scorecards</strong><small>This composition uses KPI Performance only.</small></div><b>0%</b></div>}</div></section></div>
      <section className="scorecard-detail-data"><header className="scorecard-detail-unified-header"><div><Target size={18}/><span><strong>Composition Details</strong><small>KPI Configurations and Linked Scorecards in one view.</small></span></div><span>{kpis.length + links.length} items</span></header><div className="scorecard-detail-tabs-header"><div className="scorecard-detail-table-tools"><label><Search size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search KPI or Linked Scorecard..."/></label><select value="ALL" disabled aria-label="Composition type"><option value="ALL">All Composition</option></select></div></div>
        <CompositionSection title="KPI Configurations" count={filteredKpis.length} period={periodKey} icon={<Target size={17}/>}><table className="kpi-table scorecard-detail-table"><thead><tr><th>Config Code</th><th>KPI</th><th>Weight</th><th>Category</th><th>Goal</th><th>Measurement Unit</th><th>Data Source</th><th>Actions</th></tr></thead><tbody>{filteredKpis.map((row) => <tr key={row.id}><td><span className="code-pill">{row.configurationCode}</span></td><td><strong className="scorecard-detail-kpi-name">{row.definitionName}</strong><small className="scorecard-detail-kpi-code">{row.definitionCode}</small></td><td><span className="weight-pill">{Number(row.weight)}%</span></td><td>{row.categoryName || "—"}</td><td>{row.goal || "—"}</td><td>{row.measurementUnit || "—"}</td><td>{row.dataSource || "—"}</td><td><Link className="icon-button view" title="View KPI Configuration" to={`/app/kpi-management/config/detail-record?kpiConfigCode=${encodeURIComponent(row.configurationCode)}`}><Eye size={14}/></Link></td></tr>)}{!filteredKpis.length && <tr><td colSpan={8}>No KPI Configurations match this view.</td></tr>}</tbody></table></CompositionSection>
        <CompositionSection title="Linked Scorecards" count={filteredLinks.length} period={periodKey} icon={<Link2 size={17}/>} linked><table className="kpi-table scorecard-detail-table linked-scorecard-table"><thead><tr><th>Code</th><th>Linked Scorecard</th><th>Companies</th><th>Departments</th><th>Weight</th><th>Actions</th></tr></thead><tbody>{filteredLinks.map((row) => <tr key={row.id}><td><span className="code-pill">{row.code}</span></td><td><strong className="scorecard-detail-kpi-name">{row.name}</strong><small className="scorecard-detail-kpi-code">Linked composition</small></td><td>{row.companies.join(", ") || "—"}</td><td>{row.departments.join(", ") || "—"}</td><td><span className="weight-pill linked">{Number(row.weight)}%</span></td><td><Link className="icon-button view" title="View Linked Scorecard" to={`/app/scorecards/detail?scorecardId=${row.linkedScorecardId}`}><Eye size={14}/></Link></td></tr>)}{!filteredLinks.length && <tr><td colSpan={6}>No Linked Scorecards match this view.</td></tr>}</tbody></table></CompositionSection>
        <footer className="scorecard-detail-table-footer"><span>{kpis.length} KPI Configurations · {links.length} Linked Scorecards</span><span>{totalWeight}% total composition weight</span></footer></section>
    </>}
    <Link className="scorecard-detail-back" to="/app/scorecards/overview"><ArrowLeft size={15}/> Back to Scorecard Overview</Link>
  </main>;
}

function Fact({ icon, label, value, extra }: { icon: React.ReactNode; label: string; value: string; extra?: string }) { return <article className="scorecard-detail-fact"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong>{extra && <em>{extra}</em>}</div></article>; }
function CompositionSection({ title, count, period, icon, linked = false, children }: { title: string; count: number; period: string; icon: React.ReactNode; linked?: boolean; children: React.ReactNode }) { return <section className={`scorecard-detail-unified-section ${linked ? "linked" : ""}`}><header><div>{icon}<span><strong>{title}</strong><small>{count} records for {formatPeriod(period)}</small></span></div></header><div className="scorecard-detail-table-wrap">{children}</div></section>; }
