import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, Check, Eye, Info, Link2, Search, Target, X } from "lucide-react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { compareSortValues, SortableTableHeader, type SortDirection } from "../../components/SortableTableHeader";
import { scorecardService, ScorecardApiError, type AvailableLinkedScorecard, type AvailableScorecardKpi } from "./scorecard.service";
import "../kpi-pool/kpi-pool.css";
import "../kpi-pool/manage-pool-selector.css";
import "./scorecard-assignment.css";
import "./select-assignment-items.css";

type KpiOption = AvailableScorecardKpi;
type LinkOption = AvailableLinkedScorecard;
type Option = KpiOption | LinkOption;
type AvailabilityFilter = "ALL" | "AVAILABLE" | "SELECTED" | "OCCUPIED" | "WAITING" | "NOT_AVAILABLE";
type Conflict = { kpiConfigurationCode?: string; kpiName?: string; linkedScorecardId?: string; scorecardCode?: string; scorecardName?: string; reasonCode: string; periodKey: string };

const formatPeriod = (periodKey: string, bullet = false) => {
  const [year, month] = periodKey.split("-").map(Number);
  if (!year || !month) return periodKey;
  const monthName = new Intl.DateTimeFormat("en", { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1)));
  return `${monthName}${bullet ? " • " : " "}${year}`;
};
const title = (value: string) => value.toLowerCase().replace(/_/g, " ").replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const linkReason = (code: string | null) => ({ SELF_REFERENCE: "Self-reference is not allowed", CIRCULAR_REFERENCE: "Circular dependency", INACTIVE_SCORECARD: "Inactive Scorecard", INPUT_PERIOD_NOT_AVAILABLE: "Input Period unavailable", LINKED_COMPOSITION_NOT_AVAILABLE: "Period composition unavailable" }[code ?? ""] ?? "Not available");

export function SelectAssignmentItems({ type: routeType }: { type?: string }) {
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const scorecardId = Number(params.get("scorecardId") ?? 0);
  const periodKey = params.get("period") ?? "";
  const type = (routeType ?? params.get("type")) === "linked" ? "linked" : "kpi";
  const isKpi = type === "kpi";
  const [search, setSearch] = useState("");
  const [availability, setAvailability] = useState<AvailabilityFilter>("ALL");
  const [categoryFilter, setCategoryFilter] = useState("ALL");
  const [dataSourceFilter, setDataSourceFilter] = useState("ALL");
  const [stateFilter, setStateFilter] = useState("ALL");
  const [periodCompositionFilter, setPeriodCompositionFilter] = useState("ALL");
  const [dependencyStatusFilter, setDependencyStatusFilter] = useState("ALL");
  const [linkedSort, setLinkedSort] = useState<{ key: "availability" | "scorecard" | "departments" | "composition" | "dependency"; direction: SortDirection }>({ key: "scorecard", direction: "asc" });
  const [selected, setSelected] = useState<string[]>([]);
  const [removed, setRemoved] = useState<string[]>([]);
  const [unlinked, setUnlinked] = useState<string[]>([]);
  const [dependenciesExpanded, setDependenciesExpanded] = useState(false);
  const [unlinkConfirmOpen, setUnlinkConfirmOpen] = useState(false);
  const [conflicts, setConflicts] = useState<Conflict[] | null>(null);
  const [restrictedExpanded, setRestrictedExpanded] = useState(false);
  const assignmentUrl = `/app/scorecards/assignment?scorecardId=${scorecardId}&period=${encodeURIComponent(periodKey)}`;
  const scorecard = useQuery({ queryKey: ["scorecard", scorecardId], queryFn: () => scorecardService.getById(scorecardId), enabled: scorecardId > 0 });
  const scorecardDirectory = useQuery({ queryKey: ["scorecards"], queryFn: scorecardService.list, enabled: !isKpi, staleTime: 60 * 1000 });
  const composition = useQuery({ queryKey: ["scorecard-composition", scorecardId, periodKey], queryFn: () => scorecardService.composition(scorecardId, periodKey), enabled: scorecardId > 0 && Boolean(periodKey) });
  const items = useQuery<Option[]>({ queryKey: ["scorecard-available", type, scorecardId, periodKey], queryFn: async () => isKpi ? scorecardService.availableKpis(scorecardId, periodKey) : scorecardService.availableLinks(scorecardId, periodKey), enabled: scorecardId > 0 && Boolean(periodKey) });
  const category = (row: Option): AvailabilityFilter => {
    if (isKpi) return row.selectionStatus === "AVAILABLE_TO_SELECT" ? "AVAILABLE" : row.selectionStatus === "SELECTED_IN_SCORECARD" ? "SELECTED" : row.selectionStatus === "ASSIGNED_TO_ANOTHER_SCORECARD" ? "OCCUPIED" : "NOT_AVAILABLE";
    return row.selectionStatus === "AVAILABLE_TO_LINK" ? "AVAILABLE" : row.selectionStatus === "LINKED_THIS_PERIOD" || row.selectionStatus === "SELECTED_IN_SCORECARD" || row.selectionStatus === "LINKED_WAITING_FOR_FINALIZATION" ? "SELECTED" : "NOT_AVAILABLE";
  };
  const visible = useMemo(() => (items.data ?? []).filter((row) => {
    const text = "definitionCode" in row ? `${row.definitionCode} ${row.definitionName} ${row.configurationCode} ${row.assignedScorecard?.code ?? ""} ${row.assignedScorecard?.name ?? ""}` : `${row.code} ${row.name} ${row.status} ${row.compositionStatus ?? "NOT_STARTED"}`;
    const kpi = "definitionCode" in row ? row : null;
    const linked = "definitionCode" in row ? null : row;
    const linkedCategory = linked ? category(linked) : null;
    const dependencyStatus = linked ? linkedCategory !== "SELECTED" ? "NOT_APPLICABLE" : linked.compositionStatus === "FINALIZED" ? "READY" : "WAITING" : null;
    return (!isKpi && linked && linked.id === String(scorecardId) ? false : true) && text.toLowerCase().includes(search.trim().toLowerCase()) && (availability === "ALL" || category(row) === availability) && (!kpi || categoryFilter === "ALL" || kpi.categoryName === categoryFilter) && (!kpi || dataSourceFilter === "ALL" || kpi.dataSource === dataSourceFilter) && (!kpi || stateFilter === "ALL" || kpi.status === stateFilter) && (!linked || periodCompositionFilter === "ALL" || (linked.compositionStatus ?? "NOT_STARTED") === periodCompositionFilter) && (!linked || dependencyStatusFilter === "ALL" || dependencyStatus === dependencyStatusFilter);
  }), [items.data, search, availability, isKpi, categoryFilter, dataSourceFilter, stateFilter, periodCompositionFilter, dependencyStatusFilter]);
  const count = (filter: AvailabilityFilter) => (items.data ?? []).filter((row) => category(row) === filter).length;
  const linkCandidates = !isKpi ? (items.data ?? []).filter((row): row is LinkOption => !("definitionCode" in row) && row.id !== String(scorecardId)) : [];
  const linkCount = (filter: AvailabilityFilter) => linkCandidates.filter((row) => category(row) === filter).length;
  const availableCount = isKpi ? count("AVAILABLE") : linkCount("AVAILABLE");
  const includedCount = isKpi ? count("SELECTED") + count("WAITING") : linkCount("SELECTED");
  const restrictedCount = isKpi ? count("OCCUPIED") + count("NOT_AVAILABLE") : linkCount("NOT_AVAILABLE");
  const occupiedKpis = isKpi ? (items.data ?? []).filter((row): row is KpiOption => "definitionCode" in row && row.selectionStatus === "ASSIGNED_TO_ANOTHER_SCORECARD") : [];
  const restrictedGroups = useMemo(() => [...new Map(occupiedKpis.filter((row) => row.assignedScorecard).map((row) => [row.assignedScorecard!.id, { scorecard: row.assignedScorecard!, rows: occupiedKpis.filter((item) => item.assignedScorecard?.id === row.assignedScorecard!.id) }])).values()], [occupiedKpis]);
  const waitingLinks = !isKpi ? (items.data ?? []).filter((row): row is LinkOption => !("definitionCode" in row) && row.selectionStatus === "LINKED_WAITING_FOR_FINALIZATION") : [];
  const refresh = async () => Promise.all([queryClient.invalidateQueries({ queryKey: ["scorecard-composition", scorecardId, periodKey] }), queryClient.invalidateQueries({ queryKey: ["scorecard-available", type, scorecardId, periodKey] })]);
  const add = useMutation({ mutationFn: async () => { if (!isKpi) return scorecardService.addLinks(scorecardId, periodKey, selected.map((linkedScorecardId) => ({ linkedScorecardId, weight: 0 }))); if (selected.length) await scorecardService.addKpis(scorecardId, periodKey, selected.map((poolMembershipExternalId) => ({ poolMembershipExternalId, weight: 0 }))); await Promise.all(removed.map((configurationId) => scorecardService.removeKpi(scorecardId, periodKey, configurationId))); }, onSuccess: async () => { await refresh(); navigate(assignmentUrl); }, onError: async (error) => { if (error instanceof ScorecardApiError && error.status === 409 && ["SCORECARD_KPI_ASSIGNMENT_CONFLICT", "LINKED_SCORECARD_CONFLICT"].includes(error.code)) { const details = error.details as { conflicts?: Conflict[] } | undefined; setConflicts(details?.conflicts ?? []); setSelected([]); await refresh(); } } });
  const unlink = useMutation({ mutationFn: async () => { for (const linkedScorecardId of unlinked) await scorecardService.removeLink(scorecardId, periodKey, linkedScorecardId); }, onSuccess: async () => { setUnlinked([]); setUnlinkConfirmOpen(false); await refresh(); navigate(assignmentUrl); } });
  const pageTitle = isKpi ? "Select KPIs from Pool" : "Select Linked Scorecards";
  const filters = isKpi ? [["ALL", "All"], ["AVAILABLE", "Available"], ["SELECTED", "Selected by this Scorecard"], ["OCCUPIED", "Used by another Scorecard"], ["NOT_AVAILABLE", "Not Available"]] : [["ALL", "All"], ["AVAILABLE", "Available to Link"], ["SELECTED", "Linked This Period"], ["NOT_AVAILABLE", "Not Available"]];
  const kpiOptions = isKpi ? (items.data ?? []).filter((row): row is KpiOption => "definitionCode" in row) : [];
  const categories = [...new Set(kpiOptions.map((row) => row.categoryName).filter((value): value is string => Boolean(value)))].sort();
  const dataSources = [...new Set(kpiOptions.map((row) => row.dataSource).filter((value): value is string => Boolean(value)))].sort();
  const changeCount = selected.length + removed.length;
  const candidateScorecards = linkCandidates.length;
  const linkedReadyCount = linkCandidates.filter((row) => category(row) === "SELECTED" && row.compositionStatus === "FINALIZED").length;
  const linkedWaitingCount = linkCandidates.filter((row) => category(row) === "SELECTED" && row.compositionStatus !== "FINALIZED").length;
  const selectedUnlinkRows = linkCandidates.filter((row) => unlinked.includes(row.id));
  const sortedVisible = useMemo(() => isKpi ? visible : [...visible].sort((left, right) => {
    if ("definitionCode" in left || "definitionCode" in right) return 0;
    const leftDepartments = left.departments?.join(", ") ?? "";
    const rightDepartments = right.departments?.join(", ") ?? "";
    const value = (row: LinkOption, departments: string) => linkedSort.key === "availability" ? category(row) : linkedSort.key === "scorecard" ? `${row.code} ${row.name}` : linkedSort.key === "departments" ? departments : linkedSort.key === "composition" ? row.compositionStatus ?? "NOT_STARTED" : category(row) !== "SELECTED" ? "NOT_APPLICABLE" : row.compositionStatus === "FINALIZED" ? "READY" : "WAITING";
    return compareSortValues(value(left, leftDepartments), value(right, rightDepartments), linkedSort.direction);
  }), [visible, isKpi, linkedSort]);
  const sortLinkedBy = (key: typeof linkedSort.key) => setLinkedSort((current) => ({ key, direction: current.key === key && current.direction === "asc" ? "desc" : "asc" }));

  return <main className="pool-page manage-kpis-page assignment-selection-page">
    <nav className="kpi-breadcrumb" aria-label="Breadcrumb"><Link to="/app/scorecards/overview">Scorecards</Link><span>/</span><Link to={assignmentUrl}>Scorecard Assignment</Link><span>/</span><span aria-current="page">{pageTitle}</span></nav>
    <header className="pool-page-header assignment-selection-header"><div><h1>{pageTitle}</h1><p>{isKpi ? "Choose KPI Configurations from the finalized Pool Composition for this Input Period." : "Choose eligible Scorecards for this exact Input Period."}</p></div></header>
    {scorecard.data && <><section className="manage-pool-identity-card" aria-label="Current Scorecard"><span>Scorecard</span><strong>{scorecard.data.code}<span aria-hidden="true"> · </span>{scorecard.data.name}</strong></section>{isKpi ? <section className="manage-compact-period-context assignment-selection-period" aria-label="Assignment period context"><div className="manage-period-selector-block"><span>Selected Input Period</span><div className="assignment-period-value">{formatPeriod(periodKey, true)} <small>Exact period</small></div><div className="manage-period-guidance"><small><strong>Pool Source:</strong> {scorecard.data.poolSource}</small></div></div><button type="button" className="button secondary" onClick={() => navigate(assignmentUrl)}><ArrowLeft size={16}/> Back to Assignment</button></section> : <section className="linked-selection-context" aria-label="Linked Scorecard context"><div><span>Input Period</span><strong>{formatPeriod(periodKey, true)}</strong></div><div><span>Pool Source</span><strong>{scorecard.data.poolSource}</strong></div></section>}</>}
    {isKpi ? <section className="selection-summary assignment-kpi-summary" aria-label="Selection summary"><header><div><h2>Selection Summary — {formatPeriod(periodKey)}</h2><p>How this Pool composition is currently distributed for this Scorecard.</p></div></header><div className="assignment-kpi-summary-metrics"><span><strong>{items.data?.length ?? 0}</strong> Pool KPIs</span><span><strong>{includedCount}</strong> Selected by this Scorecard</span><span><strong>{restrictedCount}</strong> Used by other Scorecards</span><span><strong>{availableCount}</strong> Available</span></div><div className="assignment-kpi-distribution" role="img" aria-label={`${includedCount} selected by this Scorecard, ${restrictedCount} used by other Scorecards, ${availableCount} available`}><span className="mine" style={{ width: `${items.data?.length ? includedCount / items.data.length * 100 : 0}%` }}/><span className="others" style={{ width: `${items.data?.length ? restrictedCount / items.data.length * 100 : 0}%` }}/><span className="free" style={{ width: `${items.data?.length ? availableCount / items.data.length * 100 : 0}%` }}/></div><div className="assignment-kpi-distribution-legend"><span><i className="mine"/>{scorecard.data?.code ?? "This Scorecard"}: {includedCount}</span><span><i className="others"/>Other Scorecards: {restrictedCount}</span><span><i className="free"/>Available: {availableCount}</span></div></section> : <section className="selection-summary linked-selection-summary" aria-label="Selection summary"><header><div><h2>Selection Summary — {formatPeriod(periodKey)}</h2><p><strong>{candidateScorecards}</strong> other Scorecard{candidateScorecards === 1 ? "" : "s"} evaluated for this Input Period</p></div>{availability !== "ALL" && <button type="button" onClick={() => setAvailability("ALL")}>View all evaluated Scorecards</button>}</header><div><button type="button" className={availability === "AVAILABLE" ? "active available" : "available"} onClick={() => setAvailability((current) => current === "AVAILABLE" ? "ALL" : "AVAILABLE")}><span>Available</span><strong>{availableCount}</strong></button><button type="button" className={availability === "SELECTED" ? "active linked" : "linked"} onClick={() => setAvailability((current) => current === "SELECTED" ? "ALL" : "SELECTED")}><span>Linked</span><strong>{includedCount}</strong><small><b>{linkedReadyCount}</b> Ready · <b>{linkedWaitingCount}</b> Waiting</small></button><button type="button" className={availability === "NOT_AVAILABLE" ? "active unavailable" : "unavailable"} onClick={() => setAvailability((current) => current === "NOT_AVAILABLE" ? "ALL" : "NOT_AVAILABLE")}><span>Unavailable</span><strong>{restrictedCount}</strong></button></div></section>}
    {!!occupiedKpis.length && <section className="assignment-selection-notice restricted compact"><AlertTriangle size={19}/><div><strong>{occupiedKpis.length} KPI{occupiedKpis.length === 1 ? " is" : "s are"} already assigned to another Scorecard.</strong>{restrictedGroups.map((group) => <p key={group.scorecard.id}><b>{group.scorecard.code} · {group.scorecard.name}</b><span>uses {group.rows.length} KPI{group.rows.length === 1 ? "" : "s"} for {formatPeriod(periodKey)}.</span></p>)}<button type="button" onClick={() => setRestrictedExpanded((value) => !value)}>{restrictedExpanded ? "Hide restricted KPIs" : "View restricted KPIs"}</button>{restrictedExpanded && <div className="assignment-restricted-details">{occupiedKpis.map((row) => <span key={row.poolMembershipExternalId}><b>{row.configurationCode}</b>{row.definitionName}</span>)}</div>}</div></section>}
    {!!waitingLinks.length && <section className="assignment-selection-notice pending linked-dependency-notice"><Info size={19}/><div><strong>Linked dependency pending · {waitingLinks.length}</strong>{waitingLinks.slice(0, dependenciesExpanded ? waitingLinks.length : 3).map((row) => <p key={row.id}><b>{row.code} · {row.name}</b><span>{formatPeriod(periodKey)} composition: {title(row.compositionStatus ?? "NOT_STARTED")}</span><button type="button" onClick={() => navigate(`/app/scorecards/detail?scorecardId=${row.id}`)}>View Scorecard</button></p>)}{waitingLinks.length > 3 && <button type="button" className="view-all-dependencies" onClick={() => setDependenciesExpanded((value) => !value)}>{dependenciesExpanded ? "Show fewer dependencies" : `View all dependencies (${waitingLinks.length})`}</button>}<small>This link can remain, but {scorecard.data?.code} cannot be finalized until {waitingLinks.length === 1 ? "this composition is" : "these compositions are"} finalized.</small></div></section>}
    {!isKpi && composition.data?.status === "FINALIZED" && <section className="linked-read-only-notice"><Check size={18}/><div><strong>Linked Scorecards are read-only</strong><span>This composition is finalized for {formatPeriod(periodKey)} and its links can no longer be modified.</span></div></section>}
    {items.isError ? <section className="scorecard-empty-state"><h2>Eligible records could not be loaded</h2><p>{(items.error as Error).message}</p></section> : <section className="manage-table-section assignment-selection-records">
      <div className="manage-section-heading manage-table-heading"><div><h2>{pageTitle} for {formatPeriod(periodKey)}</h2><p>{isKpi ? "The exact finalized Pool Composition is the only source of KPIs." : "Lifecycle and period composition are shown separately."}</p></div><span className="assignment-selection-heading-icon">{isKpi ? <Target size={19}/> : <Link2 size={19}/>}</span></div>
      <div className={`manage-toolbar assignment-selection-toolbar ${isKpi ? "kpi-selection-filters" : ""}`}><label className="pool-search"><Search size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={isKpi ? "Search KPI Configuration..." : "Search Scorecard..."}/></label><label className="assignment-availability-filter"><span>Availability</span><select value={availability} onChange={(event) => setAvailability(event.target.value as AvailabilityFilter)}>{filters.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{isKpi && <><label className="assignment-availability-filter"><span>Category</span><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="ALL">All Categories</option>{categories.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="assignment-availability-filter"><span>Data Source</span><select value={dataSourceFilter} onChange={(event) => setDataSourceFilter(event.target.value)}><option value="ALL">All Data Sources</option>{dataSources.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="assignment-availability-filter"><span>State</span><select value={stateFilter} onChange={(event) => setStateFilter(event.target.value)}><option value="ALL">All States</option>{[...new Set(kpiOptions.map((row) => row.status).filter(Boolean))].map((value) => <option key={value} value={value}>{title(value!)}</option>)}</select></label></>}</div>
      {!isKpi && <div className="linked-secondary-filters"><label className="assignment-availability-filter"><span>Period Composition</span><select value={periodCompositionFilter} onChange={(event) => setPeriodCompositionFilter(event.target.value)}><option value="ALL">All Period Compositions</option><option value="PREPARING">Preparing</option><option value="FINALIZED">Finalized</option><option value="NOT_STARTED">Not Started</option></select></label><label className="assignment-availability-filter"><span>Dependency Status</span><select value={dependencyStatusFilter} onChange={(event) => setDependencyStatusFilter(event.target.value)}><option value="ALL">All Dependency Statuses</option><option value="READY">Ready</option><option value="WAITING">Waiting for Finalization</option><option value="NOT_APPLICABLE">Not Applicable</option></select></label></div>}
      <div className="pool-inner-table manage-kpi-table-wrap stable-table-shell"><table className="kpi-table manage-kpi-table editable-table assignment-selection-table"><thead><tr><th>Select</th>{isKpi ? <><th>Availability</th><th>Config Code</th><th>KPI Code</th><th>KPI Name</th><th>Category</th><th>Goal</th><th>Measurement Unit</th><th>Data Source</th><th>Used By</th><th>State</th><th>Actions</th></> : <><SortableTableHeader active={linkedSort.key === "availability"} direction={linkedSort.direction} onSort={() => sortLinkedBy("availability")}>Availability</SortableTableHeader><SortableTableHeader active={linkedSort.key === "scorecard"} direction={linkedSort.direction} onSort={() => sortLinkedBy("scorecard")}>Scorecard</SortableTableHeader><SortableTableHeader active={linkedSort.key === "departments"} direction={linkedSort.direction} onSort={() => sortLinkedBy("departments")}>Departments</SortableTableHeader><SortableTableHeader active={linkedSort.key === "composition"} direction={linkedSort.direction} onSort={() => sortLinkedBy("composition")}>Period Composition</SortableTableHeader><SortableTableHeader active={linkedSort.key === "dependency"} direction={linkedSort.direction} onSort={() => sortLinkedBy("dependency")}>Dependency Status</SortableTableHeader><th>Actions</th></>}</tr></thead><tbody>
        {items.isLoading ? <tr><td colSpan={isKpi ? 12 : 7}>Loading eligible records...</td></tr> : sortedVisible.map((row) => {
          const kpi = "definitionCode" in row; const id = kpi ? row.poolMembershipExternalId : row.id; const state = category(row); const already = state === "SELECTED" || state === "WAITING"; const isRemoved = kpi && removed.includes(row.kpiConfigurationExternalId); const isUnlinked = !kpi && unlinked.includes(row.id); const disabled = state === "OCCUPIED" || state === "NOT_AVAILABLE" || (!kpi && composition.data?.status !== "PREPARING") || (kpi && already && composition.data?.status !== "PREPARING"); const checked = kpi && already ? !isRemoved : !kpi && already ? isUnlinked : selected.includes(id);
          const label = kpi ? state === "SELECTED" ? "Selected by this Scorecard" : state === "OCCUPIED" ? "Used by another Scorecard" : state === "AVAILABLE" ? "Available" : "Not Available" : already ? "Linked This Period" : state === "AVAILABLE" ? "Available to Link" : "Not Available";
          const periodComposition = kpi ? "" : row.compositionStatus ?? "NOT_STARTED";
          const assignmentTitle = kpi ? state === "SELECTED" ? `This KPI is currently selected by this Scorecard for ${formatPeriod(periodKey)}.` : row.assignedScorecard ? `This KPI is already used by ${row.assignedScorecard.code} for ${formatPeriod(periodKey)}.` : undefined : undefined;
          const toggle = () => { if (kpi && already) setRemoved((current) => current.includes(row.kpiConfigurationExternalId) ? current.filter((value) => value !== row.kpiConfigurationExternalId) : [...current, row.kpiConfigurationExternalId]); else if (!kpi && already) setUnlinked((current) => current.includes(row.id) ? current.filter((value) => value !== row.id) : [...current, row.id]); else setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); };
          const linkedDepartments = !kpi ? row.departments?.length ? row.departments : scorecardDirectory.data?.find((candidate) => String(candidate.id) === row.id)?.departments ?? [] : [];
          return <tr key={id} title={assignmentTitle} className={`${checked ? "selected-row" : ""} ${disabled && !already ? "assignment-occupied-row" : ""}`}><td><input type="checkbox" disabled={disabled} checked={checked} aria-label={label} onChange={toggle}/></td><td><span className={`availability-label ${state.toLowerCase()}`}><strong>{label}</strong>{!kpi && row.reasonCode && <small>{linkReason(row.reasonCode)}</small>}</span></td>{kpi ? <><td><span className="code-pill">{row.configurationCode}</span></td><td className="name-cell">{row.definitionCode}</td><td className="name-cell">{row.definitionName}</td><td>{row.categoryName || "—"}</td><td>{row.goal || "—"}</td><td>{row.measurementUnit || "—"}</td><td>{row.dataSource || "—"}</td><td><span className={`assignment-owner ${state.toLowerCase()}`}>{state === "SELECTED" ? <><strong>This Scorecard</strong><small>{scorecard.data?.code}</small></> : row.assignedScorecard ? <><strong>{row.assignedScorecard.code}</strong><small>{row.assignedScorecard.name}</small></> : <strong>—</strong>}</span></td><td>{row.status ? <span className={`assignment-option-status ${row.status.toLowerCase()}`}>{title(row.status)}</span> : "—"}</td><td><button type="button" className="icon-button view" title="View KPI Configuration detail" onClick={() => navigate(`/app/kpi-management/config/detail-record?kpiConfigCode=${encodeURIComponent(row.configurationCode)}`)}><Eye size={14}/></button></td></> : <><td className="linked-scorecard-identity"><span className="code-pill">{row.code}</span><strong>{row.name}</strong></td><td title={linkedDepartments.join(", ") || "No departments available"}>{linkedDepartments.length > 1 ? `${linkedDepartments.length} Departments` : linkedDepartments[0] || "—"}</td><td><span className={`assignment-period-composition ${periodComposition.toLowerCase()}`}>{title(periodComposition)}</span></td><td>{already ? periodComposition === "FINALIZED" ? <span className="linked-dependency ready">Ready</span> : <span className="linked-dependency waiting">Waiting for Finalization</span> : <span className="linked-dependency not-applicable">Not Applicable</span>}</td><td><button type="button" className="icon-button view" title="View Scorecard Details" onClick={() => navigate(`/app/scorecards/detail?scorecardId=${row.id}`)}><Eye size={14}/></button></td></>}</tr>;
        })}
        {!items.isLoading && !visible.length && <tr><td colSpan={isKpi ? 12 : 7}><div className="assignment-selection-empty"><Search size={24}/><strong>No matching records found</strong><span>Try another search or availability filter.</span></div></td></tr>}
      </tbody></table><footer className="manage-actions assignment-selection-actions"><span><strong>{isKpi ? changeCount : selected.length + unlinked.length}</strong> {isKpi ? "changes" : `${selected.length + unlinked.length === 1 ? "row" : "rows"} selected`}</span><button type="button" className="button secondary manage-back-button" onClick={() => navigate(assignmentUrl)}><ArrowLeft size={16}/> Back to Assignment</button><div>{!isKpi && <button className="button unlink-selected" disabled={!unlinked.length || unlink.isPending || composition.data?.status !== "PREPARING"} onClick={() => setUnlinkConfirmOpen(true)}>{`Unlink Selected (${unlinked.length})`}</button>}<button className="button pool-link-selected" disabled={!(isKpi ? changeCount : selected.length) || add.isPending || (!isKpi && composition.data?.status !== "PREPARING")} onClick={() => add.mutate()}>{isKpi ? <Check size={16}/> : <Link2 size={16}/>} {add.isPending ? "Saving..." : isKpi ? `Apply Selection (${changeCount})` : `Link Selected (${selected.length})`}</button></div></footer></div>
      {add.error && !conflicts && <p className="scorecard-form-error">{(add.error as Error).message}</p>}
      {unlink.error && <p className="scorecard-form-error">{(unlink.error as Error).message}</p>}
    </section>}
    {conflicts && <div className="assignment-conflict-backdrop" role="presentation"><section className="assignment-conflict-dialog" role="dialog" aria-modal="true" aria-labelledby="selection-conflict-title"><header><span><AlertTriangle size={21}/></span><div><h2 id="selection-conflict-title">{isKpi ? "Selection changed" : "Linked Scorecard selection changed"}</h2><p>{isKpi ? `One or more KPIs are no longer available for ${formatPeriod(periodKey)}.` : "We couldn't save this selection because one or more Scorecards are no longer eligible."}</p></div><button type="button" aria-label="Close" onClick={() => setConflicts(null)}><X size={18}/></button></header><div className="assignment-conflict-period">{formatPeriod(periodKey, true)}</div><div className="assignment-conflict-list">{conflicts.map((conflict, index) => <article key={`${conflict.kpiConfigurationCode ?? conflict.linkedScorecardId}-${index}`}><strong>{conflict.kpiConfigurationCode ?? conflict.scorecardCode ?? "Selection conflict"}</strong>{conflict.kpiName && <span>{conflict.kpiName}</span>}<small>Reason: {conflict.reasonCode === "ASSIGNED_TO_ANOTHER_SCORECARD" ? "Assigned to another Scorecard" : linkReason(conflict.reasonCode)}</small>{conflict.scorecardCode && <b>Currently Used By: {conflict.scorecardCode} · {conflict.scorecardName}</b>}</article>)}</div><p className="assignment-conflict-atomic">No changes were saved.</p><footer><button type="button" className="button primary" onClick={() => setConflicts(null)}>Review Selection</button></footer></section></div>}
    {unlinkConfirmOpen && <div className="assignment-conflict-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !unlink.isPending) setUnlinkConfirmOpen(false); }}><section className="assignment-conflict-dialog unlink-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="unlink-confirm-title"><header><span><AlertTriangle size={21}/></span><div><h2 id="unlink-confirm-title">Unlink selected Scorecards?</h2><p>The selected links and their assigned weight contributions will be removed from {formatPeriod(periodKey)}.</p></div><button type="button" aria-label="Close" disabled={unlink.isPending} onClick={() => setUnlinkConfirmOpen(false)}><X size={18}/></button></header><div className="assignment-conflict-list">{selectedUnlinkRows.map((row) => <article key={row.id}><strong>{row.code}</strong><span>{row.name}</span></article>)}</div><p className="assignment-conflict-atomic">Review Composition Weight after unlinking these Scorecards.</p><footer><button type="button" className="button secondary" disabled={unlink.isPending} onClick={() => setUnlinkConfirmOpen(false)}>Cancel</button><button type="button" className="button unlink-selected" disabled={unlink.isPending} onClick={() => unlink.mutate()}>{unlink.isPending ? "Unlinking..." : `Unlink ${unlinked.length} Scorecard${unlinked.length === 1 ? "" : "s"}`}</button></footer></section></div>}
  </main>;
}
