-- EXA KPI Pool Service initial schema (MySQL 8.4, UTF-8 without BOM).
-- Cross-service references are scalar External IDs and never physical FKs.

CREATE TABLE `pool_areas` (
  `pool_area_id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `display_order` SMALLINT NOT NULL DEFAULT 1,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by_user_id` BIGINT NULL,
  `updated_at` DATETIME(3) NULL,
  `updated_by_user_id` BIGINT NULL,
  PRIMARY KEY (`pool_area_id`),
  UNIQUE INDEX `uq_pool_areas_code` (`code`),
  INDEX `ix_pool_areas_lookup` (`is_active`, `display_order`, `code`),
  CONSTRAINT `chk_pool_areas_code_not_blank` CHECK (CHAR_LENGTH(TRIM(`code`)) > 0),
  CONSTRAINT `chk_pool_areas_name_not_blank` CHECK (CHAR_LENGTH(TRIM(`name`)) > 0),
  CONSTRAINT `chk_pool_areas_display_order` CHECK (`display_order` > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `company_references` (
  `external_company_id` BIGINT NOT NULL,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `display_order` SMALLINT NOT NULL DEFAULT 1,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `source_version` BIGINT NULL,
  `source_updated_at` DATETIME(3) NULL,
  `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`external_company_id`),
  UNIQUE INDEX `uq_company_references_code` (`code`),
  INDEX `ix_company_references_lookup` (`is_active`, `display_order`, `code`),
  CONSTRAINT `chk_company_references_code_not_blank` CHECK (CHAR_LENGTH(TRIM(`code`)) > 0),
  CONSTRAINT `chk_company_references_name_not_blank` CHECK (CHAR_LENGTH(TRIM(`name`)) > 0),
  CONSTRAINT `chk_company_references_display_order` CHECK (`display_order` > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `input_frequency_references` (
  `external_input_frequency_id` BIGINT NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `months_per_period` SMALLINT NOT NULL,
  `periods_per_year` SMALLINT NULL,
  `display_order` SMALLINT NOT NULL DEFAULT 1,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `source_version` BIGINT NULL,
  `source_updated_at` DATETIME(3) NULL,
  `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`external_input_frequency_id`),
  UNIQUE INDEX `uq_input_frequency_references_code` (`code`),
  INDEX `ix_input_frequency_references_lookup` (`is_active`, `display_order`, `code`),
  CONSTRAINT `chk_input_frequency_references_code_not_blank` CHECK (CHAR_LENGTH(TRIM(`code`)) > 0),
  CONSTRAINT `chk_input_frequency_references_name_not_blank` CHECK (CHAR_LENGTH(TRIM(`name`)) > 0),
  CONSTRAINT `chk_input_frequency_references_months` CHECK (`months_per_period` > 0),
  CONSTRAINT `chk_input_frequency_references_periods` CHECK (`periods_per_year` IS NULL OR `periods_per_year` > 0),
  CONSTRAINT `chk_input_frequency_references_display_order` CHECK (`display_order` > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `kpi_pool_code_sequences` (
  `kpi_pool_code_sequence_id` BIGINT NOT NULL AUTO_INCREMENT,
  `area_scope_key` VARCHAR(255) NOT NULL,
  `company_scope_key` VARCHAR(255) NOT NULL,
  `issue_year` SMALLINT NOT NULL,
  `last_sequence` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`kpi_pool_code_sequence_id`),
  UNIQUE INDEX `uq_kpi_pool_code_sequence_scope` (`area_scope_key`, `company_scope_key`, `issue_year`),
  CONSTRAINT `chk_kpi_pool_code_sequences_area_scope` CHECK (CHAR_LENGTH(TRIM(`area_scope_key`)) > 0),
  CONSTRAINT `chk_kpi_pool_code_sequences_company_scope` CHECK (CHAR_LENGTH(TRIM(`company_scope_key`)) > 0),
  CONSTRAINT `chk_kpi_pool_code_sequences_issue_year` CHECK (`issue_year` BETWEEN 2000 AND 9999)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `kpi_pools` (
  `kpi_pool_id` BIGINT NOT NULL AUTO_INCREMENT,
  `pool_code` VARCHAR(500) NOT NULL,
  `pool_sequence` INT UNSIGNED NOT NULL,
  `issue_year` SMALLINT NOT NULL,
  `area_scope_key` VARCHAR(255) NOT NULL,
  `company_scope_key` VARCHAR(255) NOT NULL,
  `pool_name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `notes` TEXT NULL,
  `input_frequency_external_id` BIGINT NOT NULL,
  `input_frequency_code` VARCHAR(50) NOT NULL,
  `valid_from` DATE NOT NULL,
  `valid_to` DATE NOT NULL,
  `status_code` VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  `aggregate_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `deleted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by_user_id` BIGINT NULL,
  `updated_at` DATETIME(3) NULL,
  `updated_by_user_id` BIGINT NULL,
  PRIMARY KEY (`kpi_pool_id`),
  UNIQUE INDEX `uq_kpi_pools_code` (`pool_code`),
  UNIQUE INDEX `uq_kpi_pools_business_scope_sequence` (`area_scope_key`, `company_scope_key`, `issue_year`, `pool_sequence`),
  INDEX `ix_kpi_pools_status` (`status_code`, `deleted_at`),
  INDEX `ix_kpi_pools_validity` (`valid_from`, `valid_to`),
  INDEX `ix_kpi_pools_input_frequency_external` (`input_frequency_external_id`),
  CONSTRAINT `chk_kpi_pools_code_not_blank` CHECK (CHAR_LENGTH(TRIM(`pool_code`)) > 0),
  CONSTRAINT `chk_kpi_pools_name_not_blank` CHECK (CHAR_LENGTH(TRIM(`pool_name`)) > 0),
  CONSTRAINT `chk_kpi_pools_area_scope` CHECK (CHAR_LENGTH(TRIM(`area_scope_key`)) > 0),
  CONSTRAINT `chk_kpi_pools_company_scope` CHECK (CHAR_LENGTH(TRIM(`company_scope_key`)) > 0),
  CONSTRAINT `chk_kpi_pools_frequency_code` CHECK (CHAR_LENGTH(TRIM(`input_frequency_code`)) > 0),
  CONSTRAINT `chk_kpi_pools_validity` CHECK (`valid_to` >= `valid_from`),
  CONSTRAINT `chk_kpi_pools_status` CHECK (`status_code` IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
  CONSTRAINT `chk_kpi_pools_sequence` CHECK (`pool_sequence` > 0),
  CONSTRAINT `chk_kpi_pools_issue_year` CHECK (`issue_year` BETWEEN 2000 AND 9999),
  CONSTRAINT `chk_kpi_pools_aggregate_version` CHECK (`aggregate_version` > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `kpi_pool_areas` (
  `kpi_pool_area_id` BIGINT NOT NULL AUTO_INCREMENT,
  `kpi_pool_id` BIGINT NOT NULL,
  `pool_area_id` BIGINT NOT NULL,
  `display_order` SMALLINT NOT NULL,
  `area_code_snapshot` VARCHAR(20) NOT NULL,
  `area_name_snapshot` VARCHAR(120) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by_user_id` BIGINT NULL,
  PRIMARY KEY (`kpi_pool_area_id`),
  UNIQUE INDEX `uq_kpi_pool_area` (`kpi_pool_id`, `pool_area_id`),
  UNIQUE INDEX `uq_kpi_pool_area_order` (`kpi_pool_id`, `display_order`),
  INDEX `ix_kpi_pool_areas_area` (`pool_area_id`),
  CONSTRAINT `chk_kpi_pool_areas_display_order` CHECK (`display_order` > 0),
  CONSTRAINT `fk_kpi_pool_areas_pool` FOREIGN KEY (`kpi_pool_id`) REFERENCES `kpi_pools` (`kpi_pool_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_kpi_pool_areas_area` FOREIGN KEY (`pool_area_id`) REFERENCES `pool_areas` (`pool_area_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `kpi_pool_companies` (
  `kpi_pool_company_id` BIGINT NOT NULL AUTO_INCREMENT,
  `kpi_pool_id` BIGINT NOT NULL,
  `external_company_id` BIGINT NOT NULL,
  `display_order` SMALLINT NOT NULL,
  `company_code_snapshot` VARCHAR(30) NOT NULL,
  `company_name_snapshot` VARCHAR(150) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by_user_id` BIGINT NULL,
  PRIMARY KEY (`kpi_pool_company_id`),
  UNIQUE INDEX `uq_kpi_pool_company` (`kpi_pool_id`, `external_company_id`),
  UNIQUE INDEX `uq_kpi_pool_company_order` (`kpi_pool_id`, `display_order`),
  INDEX `ix_kpi_pool_companies_external_company` (`external_company_id`),
  CONSTRAINT `chk_kpi_pool_companies_display_order` CHECK (`display_order` > 0),
  CONSTRAINT `fk_kpi_pool_companies_pool` FOREIGN KEY (`kpi_pool_id`) REFERENCES `kpi_pools` (`kpi_pool_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_kpi_pool_companies_company_reference` FOREIGN KEY (`external_company_id`) REFERENCES `company_references` (`external_company_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `kpi_pool_kpis` (
  `kpi_pool_kpi_id` BIGINT NOT NULL AUTO_INCREMENT,
  `kpi_pool_id` BIGINT NOT NULL,
  `kpi_definition_external_id` BIGINT NOT NULL,
  `kpi_configuration_external_id` BIGINT NOT NULL,
  `definition_code_snapshot` VARCHAR(30) NOT NULL,
  `definition_name_snapshot` VARCHAR(200) NOT NULL,
  `configuration_code_snapshot` VARCHAR(40) NOT NULL,
  `input_frequency_external_id_snapshot` BIGINT NOT NULL,
  `input_frequency_code_snapshot` VARCHAR(50) NOT NULL,
  `display_order` INT UNSIGNED NOT NULL,
  `is_required` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by_user_id` BIGINT NULL,
  PRIMARY KEY (`kpi_pool_kpi_id`),
  UNIQUE INDEX `uq_kpi_pool_configuration` (`kpi_pool_id`, `kpi_configuration_external_id`),
  UNIQUE INDEX `uq_kpi_pool_definition` (`kpi_pool_id`, `kpi_definition_external_id`),
  UNIQUE INDEX `uq_kpi_pool_kpi_order` (`kpi_pool_id`, `display_order`),
  INDEX `ix_kpi_pool_kpis_configuration_external` (`kpi_configuration_external_id`),
  INDEX `ix_kpi_pool_kpis_definition_external` (`kpi_definition_external_id`),
  CONSTRAINT `chk_kpi_pool_kpis_display_order` CHECK (`display_order` > 0),
  CONSTRAINT `fk_kpi_pool_kpis_pool` FOREIGN KEY (`kpi_pool_id`) REFERENCES `kpi_pools` (`kpi_pool_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `outbox_events` (
  `outbox_event_id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` CHAR(36) NOT NULL,
  `event_type` VARCHAR(120) NOT NULL,
  `aggregate_type` VARCHAR(80) NOT NULL,
  `aggregate_id` VARCHAR(100) NOT NULL,
  `aggregate_version` INT UNSIGNED NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `payload` JSON NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NULL,
  `last_error` TEXT NULL,
  `published_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`outbox_event_id`),
  UNIQUE INDEX `uq_outbox_events_event_id` (`event_id`),
  INDEX `ix_outbox_events_pending` (`status`, `next_attempt_at`, `occurred_at`),
  INDEX `ix_outbox_events_aggregate` (`aggregate_type`, `aggregate_id`, `aggregate_version`),
  CONSTRAINT `chk_outbox_events_event_type` CHECK (CHAR_LENGTH(TRIM(`event_type`)) > 0),
  CONSTRAINT `chk_outbox_events_aggregate_type` CHECK (CHAR_LENGTH(TRIM(`aggregate_type`)) > 0),
  CONSTRAINT `chk_outbox_events_aggregate_id` CHECK (CHAR_LENGTH(TRIM(`aggregate_id`)) > 0),
  CONSTRAINT `chk_outbox_events_subject` CHECK (CHAR_LENGTH(TRIM(`subject`)) > 0),
  CONSTRAINT `chk_outbox_events_version` CHECK (`aggregate_version` > 0),
  CONSTRAINT `chk_outbox_events_status` CHECK (`status` IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
