import { Prisma } from "@prisma/client";
import { prisma } from "../config/prisma.js";
import { kpiPoolClient } from "../clients/kpi-pool.client.js";
import { scorecardsClient } from "../clients/scorecards.client.js";
import type { AttachedScorecardsQuery,DetailInputsQuery,MonitoringListQuery,ScheduleQuery } from "../schemas/monitoring-period.schema.js";
import { AppError } from "../utils/app-error.js";

const dateOnly=(value:Date)=>value.toISOString().slice(0,10); const meta=(page:number,pageSize:number,totalItems:number)=>({page,pageSize,totalItems,totalPages:Math.ceil(totalItems/pageSize)});
const entered=(inputs:Array<{result:{resultValue:unknown}|null}>)=>inputs.filter(i=>i.result?.resultValue!==null&&i.result?.resultValue!==undefined).length;
const periodInclude={status:true,inputs:{select:{result:{select:{resultValue:true}}}}};
const periodDto=(row:any)=>{const count=entered(row.inputs);return{id:row.id.toString(),code:`MP-${row.poolCodeSnapshot}-${row.periodKey}`,poolId:row.kpiPoolExternalId.toString(),poolInputPeriodId:row.poolInputPeriodExternalId.toString(),poolCode:row.poolCodeSnapshot,poolName:row.poolNameSnapshot,companies:row.companiesSnapshot??[],periodKey:row.periodKey,periodLabel:row.periodLabel,periodStart:dateOnly(row.periodStart),periodEnd:dateOnly(row.periodEnd),status:row.status.code,frequency:row.inputFrequencyNameSnapshot,expected:row.inputs.length,entered:count,pending:row.inputs.length-count,completionPercent:row.inputs.length?Math.round(count/row.inputs.length*100):0,validationStatus:row.validationStatus,closedAt:row.closedAt?.toISOString()??null,closedWithExceptions:row.closedWithExceptions};};

export const monitoringReadService={
 async overview(query:MonitoringListQuery){
  const where:Prisma.MonitoringPeriodWhereInput={...(query.search?{OR:[{poolCodeSnapshot:{contains:query.search}},{poolNameSnapshot:{contains:query.search}},{periodLabel:{contains:query.search}}]}:{}),...(query.status.length?{status:{code:{in:query.status}}}:{}),...(query.frequency.length?{inputFrequencyNameSnapshot:{in:query.frequency}}:{}),...(query.year?{periodStart:{gte:new Date(Date.UTC(query.year,0,1)),lt:new Date(Date.UTC(query.year+1,0,1))}}:{})};
  const orderMap:any={periodStart:"periodStart",poolCode:"poolCodeSnapshot",poolName:"poolNameSnapshot",status:"statusId",frequency:"inputFrequencyNameSnapshot"};
  const rows=await prisma.monitoringPeriod.findMany({where,include:periodInclude}); let items=rows.map(periodDto);if(query.company.length)items=items.filter((item:any)=>item.companies.some((company:any)=>query.company.includes(company.code)||query.company.includes(company.name)));if(query.month.length)items=items.filter((item:any)=>query.month.includes(String(new Date(`${item.periodStart}T00:00:00Z`).getUTCMonth()+1)));
  const key=query.sortBy; items.sort((a:any,b:any)=>{const av=key==="expected"||key==="entered"?a[key]:a[orderMap[key]??key]??a[key],bv=key==="expected"||key==="entered"?b[key]:b[orderMap[key]??key]??b[key];return String(av??"").localeCompare(String(bv??""),undefined,{numeric:true})*(query.sortOrder==="asc"?1:-1)});
  const totalItems=items.length,start=(query.page-1)*query.pageSize;return{data:items.slice(start,start+query.pageSize),meta:meta(query.page,query.pageSize,totalItems),facets:{statuses:[...new Set(items.map((i:any)=>i.status))],frequencies:[...new Set(items.map((i:any)=>i.frequency).filter(Boolean))],companies:[...new Set(items.flatMap((i:any)=>i.companies.map((c:any)=>c.name)))]}};
 },
 async resolve(poolId:string,poolInputPeriodId:string){
  const [pool,periods]=await Promise.all([kpiPoolClient.get(poolId),kpiPoolClient.periods(poolId)]);const p=periods.find(x=>x.poolPeriodId===poolInputPeriodId);if(!p)throw new AppError(404,"POOL_INPUT_PERIOD_NOT_FOUND","The Input Period does not belong to this KPI Pool");
  const row=await prisma.monitoringPeriod.findUnique({where:{kpiPoolExternalId_poolInputPeriodExternalId:{kpiPoolExternalId:BigInt(poolId),poolInputPeriodExternalId:BigInt(poolInputPeriodId)}},include:periodInclude});if(row)return{pool:{id:pool.id,code:pool.poolCode,name:pool.poolName},inputPeriod:p,availability:"AVAILABLE",reasonCode:null,reason:null,monitoringPeriod:periodDto(row),action:row.status.code==="DRAFT"?"ENTER_RESULTS":row.status.code==="SUBMITTED"?"VIEW_VALIDATION":row.status.code==="VALIDATED"?"CLOSE_PERIOD":"VIEW_HISTORICAL_RESULTS"};
  if(p.workflowStatus!=="FINALIZED")return{pool:{id:pool.id,code:pool.poolCode,name:pool.poolName},inputPeriod:p,availability:"NOT_AVAILABLE",reasonCode:"POOL_COMPOSITION_NOT_FINALIZED",reason:"Waiting for Pool composition...",monitoringPeriod:null,action:"NONE"};
  const projection=await scorecardsClient.materialization(poolId,poolInputPeriodId);return{pool:{id:pool.id,code:pool.poolCode,name:pool.poolName},inputPeriod:p,availability:projection.readiness==="READY"?"READY_TO_MATERIALIZE":"NOT_AVAILABLE",reasonCode:projection.reason,reason:projection.readiness==="READY"?"Ready to create Monitoring Period":"Waiting for Scorecard compositions...",monitoringPeriod:null,action:projection.readiness==="READY"?"MATERIALIZE":"NONE"};
 },
 async detail(id:string,query:DetailInputsQuery){const period=await prisma.monitoringPeriod.findUnique({where:{id:BigInt(id)},include:{status:true,scorecards:true,inputs:{include:{result:true,scorecard:true}}}});if(!period)throw new AppError(404,"MONITORING_PERIOD_NOT_FOUND","Monitoring Period was not found");let rows=period.inputs.map((i:any)=>({id:i.id.toString(),scorecardCode:i.scorecard.scorecardCodeSnapshot,kpiCode:i.kpiCodeSnapshot,kpiName:i.kpiNameSnapshot,unit:i.measurementUnitSymbolSnapshot??i.measurementUnitNameSnapshot,goal:i.goalTextSnapshot??i.goalValueSnapshot?.toString()??null,result:i.result?.resultValue?.toString()??null,entryStatus:i.result?.resultValue!=null?"ENTERED":"PENDING",validation:i.result?.calculationStatus==="NOT_CALCULABLE"?"ERROR":i.result?.resultValue==null?"MISSING":"VALID",score:i.result?.compliancePercent?.toString()??null,weightedScore:i.result?.weightedScorePoints?.toString()??null,trafficLight:i.result?.trafficLightCode??null,comment:i.result?.comment??null}));const term=query.search?.toLowerCase();rows=rows.filter((r:any)=>(!term||`${r.kpiCode} ${r.kpiName} ${r.scorecardCode}`.toLowerCase().includes(term))&&(!query.entryStatus.length||query.entryStatus.includes(r.entryStatus))&&(!query.validation.length||query.validation.includes(r.validation))&&(!query.trafficLight.length||query.trafficLight.includes(r.trafficLight))&&(!query.unit.length||query.unit.includes(r.unit)));rows.sort((a:any,b:any)=>String(a[query.sortBy]??"").localeCompare(String(b[query.sortBy]??""),undefined,{numeric:true})*(query.sortOrder==="asc"?1:-1));const totalItems=rows.length,start=(query.page-1)*query.pageSize;return{period:periodDto({...period,inputs:period.inputs}),scorecards:period.scorecards.map((s:any)=>({id:s.id.toString(),code:s.scorecardCodeSnapshot,name:s.scorecardNameSnapshot,previewScore:s.previewScorePercent?.toString()??null,finalScore:s.finalScorePercent?.toString()??null})),data:rows.slice(start,start+query.pageSize),meta:meta(query.page,query.pageSize,totalItems)};},
 async attached(id:string,query:AttachedScorecardsQuery){const period=await prisma.monitoringPeriod.findUnique({where:{id:BigInt(id)},include:{status:true,inputs:{include:{result:true}},scorecards:{include:{inputs:{include:{result:true}}}}}});if(!period)throw new AppError(404,"MONITORING_PERIOD_NOT_FOUND","Monitoring Period was not found");let rows=period.scorecards.map((s:any)=>{const count=entered(s.inputs);return{id:s.id.toString(),externalId:s.scorecardExternalId.toString(),code:s.scorecardCodeSnapshot,name:s.scorecardNameSnapshot,departments:s.departmentsSnapshot??[],entryStatus:count===s.inputs.length?"COMPLETED":count?"IN_PROGRESS":"PENDING",expected:s.inputs.length,entered:count,pending:s.inputs.length-count,previewScore:s.previewScorePercent?.toString()??null,finalScore:s.finalScorePercent?.toString()??null,trafficLights:{green:s.inputs.filter((i:any)=>i.result?.trafficLightCode==="GREEN").length,yellow:s.inputs.filter((i:any)=>i.result?.trafficLightCode==="YELLOW").length,red:s.inputs.filter((i:any)=>i.result?.trafficLightCode==="RED").length},kpis:s.inputs.map((i:any)=>({id:i.id.toString(),code:i.kpiCodeSnapshot,name:i.kpiNameSnapshot,unit:i.measurementUnitSymbolSnapshot??i.measurementUnitNameSnapshot,goal:i.goalTextSnapshot,result:i.result?.resultValue?.toString()??null,score:i.result?.compliancePercent?.toString()??null,weight:i.weightPercentSnapshot.toString(),entryStatus:i.result?.resultValue!=null?"ENTERED":"PENDING",trafficLight:i.result?.trafficLightCode??null}))};});const term=query.search?.toLowerCase();rows=rows.filter((r:any)=>(!term||`${r.code} ${r.name}`.toLowerCase().includes(term))&&(!query.entryStatus.length||query.entryStatus.includes(r.entryStatus)));rows.sort((a:any,b:any)=>String(a[query.sortBy]??"").localeCompare(String(b[query.sortBy]??""),undefined,{numeric:true})*(query.sortOrder==="asc"?1:-1));const totalItems=rows.length,start=(query.page-1)*query.pageSize;return{period:periodDto(period),data:rows.slice(start,start+query.pageSize),meta:meta(query.page,query.pageSize,totalItems)};},
 async schedule(poolId:string,query:ScheduleQuery){const [pool,periods,monitoring]=await Promise.all([kpiPoolClient.get(poolId),kpiPoolClient.periods(poolId),prisma.monitoringPeriod.findMany({where:{kpiPoolExternalId:BigInt(poolId)},include:periodInclude})]);const byInput=new Map(monitoring.map((p:any)=>[p.poolInputPeriodExternalId.toString(),p]));let rows=periods.map((p:any)=>{const row=p.poolPeriodId?byInput.get(p.poolPeriodId):null;return{poolInputPeriodId:p.poolPeriodId,periodKey:p.periodKey,periodStart:p.start,periodEnd:p.end,poolWorkflowStatus:p.workflowStatus,monitoringPeriod:row?periodDto(row):null,status:row?.status.code??"NOT_AVAILABLE",validation:row?.validationStatus??(p.workflowStatus==="FINALIZED"?"WAITING_FOR_SCORECARDS":"LOCKED"),expected:row?.inputs.length??null,entered:row?entered(row.inputs):null,pending:row?row.inputs.length-entered(row.inputs):null,closedAt:row?.closedAt?.toISOString()??null};});const term=query.search?.toLowerCase();rows=rows.filter((r:any)=>(!term||`${r.periodKey} ${r.status} ${r.validation}`.toLowerCase().includes(term))&&(!query.status.length||query.status.includes(r.status))&&(!query.validation.length||query.validation.includes(r.validation)));rows.sort((a:any,b:any)=>String(a[query.sortBy]??"").localeCompare(String(b[query.sortBy]??""),undefined,{numeric:true})*(query.sortOrder==="asc"?1:-1));const totalItems=rows.length,start=(query.page-1)*query.pageSize;return{pool:{id:pool.id,code:pool.poolCode,name:pool.poolName,companies:pool.companies,frequency:pool.inputFrequency},data:rows.slice(start,start+query.pageSize),meta:meta(query.page,query.pageSize,totalItems)};}
};
