export type KpiConfigStatus = "CONFIGURED" | "INCOMPLETE" | "INACTIVE";
export type PeriodScope = "CURRENT_PERIOD" | "SAME_PERIOD_PREVIOUS_YEAR" | "PREVIOUS_PERIOD";
export type GoalMode = "SINGLE" | "RANGE" | "BY_SUBJECT";
export type EntityEvaluationMode = "INDIVIDUAL" | "CONTRIBUTE_TO_OVERALL";
export type EvaluationScope = "OVERALL" | "BY_SUBJECT";
export type GoalType = "SINGLE_VALUE" | "RANGE";
export type GoalAssignment = "SAME_GOAL_FOR_ALL" | "DIFFERENT_GOAL_PER_SUBJECT";
export type ResultMethod = "DIRECT" | "CALCULATED_FROM_INPUTS";
export type MeasurementInput = { name: string; unit: string; description: string };
export type CalculationTemplate = "DIVIDE" | "PERCENT_RATIO" | "SUM" | "AVERAGE" | "DIFFERENCE";
export type TargetKind = "ABSOLUTE_TARGET" | "CHANGE_TARGET" | "UPPER_LIMIT" | "LOWER_LIMIT" | "DEADLINE";
export type SubjectType = string;
export type SubjectGoal = { subjectExternalId: string; subjectCode?: string | null; subjectLabel: string; goal: number; goalUnit?: string; resultUnit?: string };
export type SubjectSelection = Omit<SubjectGoal, "goal" | "goalUnit" | "resultUnit">;
export type GroupGoal = { value: number; unit: string; label: string };

export type TrafficLightRanges = {
  redFrom: number;
  redTo: number;
  yellowFrom: number;
  yellowTo: number;
  greenFrom: number;
  greenTo: number;
};

export type KpiConfigRecord = {
  evaluationTypeCode?: string | null;
  resultSemantics?: string | null;
  scoringMethod?: string | null;
  scoringRuleConfig?: { model?: string; editorMode?: string; bandMode?: "STEP_POINTS" | "LINEAR_POINTS" | "INTERVALS"; floorPercent?: number; capPercent?: number; bands?: Array<{ minResult: number | null; maxResult?: number | null; compliance: number; includesMin?: boolean; includesMax?: boolean }> } | null;
  negativeResultPolicy?: string | null;
  id: number;
  code: string;
  definitionId: string | number;
  definitionCode: string;
  definitionName: string;
  goal: number;
  inputFrequencyCode?: string;
  inputFrequencyName?: string;
  periodScope?: PeriodScope;
  comparisonMode?: "NONE" | "SAME_PERIOD_PREVIOUS_YEAR" | "PREVIOUS_PERIOD";
  comparisonDirection?: "INCREASE" | "REDUCTION" | null;
  calculationPattern?: string | null;
  calculationTemplate?: CalculationTemplate | null;
  goalMode?: GoalMode;
  evaluationScope?: EvaluationScope;
  goalType?: GoalType;
  entityEvaluationMode?: EntityEvaluationMode | null;
  goalAssignment?: GoalAssignment | null;
  goalUnit?: string;
  resultMethod?: ResultMethod;
  measurementInputs?: MeasurementInput[];
  targetKind?: TargetKind | null;
  rangeMinGoal?: number | null;
  rangeMaxGoal?: number | null;
  subjectType?: SubjectType | null;
  subjectGoals?: SubjectGoal[];
  subjects?: SubjectSelection[];
  groupGoal?: GroupGoal | null;
  measurementUnit: string;
  evaluationType: string;
  dataSource: string;
  ranges: TrafficLightRanges;
  usedIn: number;
  status: KpiConfigStatus;
  isActive?: boolean;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  poolNames: string[];
};

export type KpiConfigInput = {
  scoringMethod?: string;
  scoringRuleConfig?: Record<string, unknown>;
  scoringRuleConfigVersion?: number;
  scoringApprovalStatus?: string;
  negativeResultPolicy?: string;
  definitionId: string | number;
  goal: number;
  inputFrequencyCode: string;
  periodScope: PeriodScope;
  goalMode: GoalMode;
  evaluationScope: EvaluationScope;
  goalType: GoalType;
  entityEvaluationMode?: EntityEvaluationMode | null;
  goalAssignment?: GoalAssignment | null;
  goalUnit?: string;
  resultMethod: ResultMethod;
  measurementInputs: MeasurementInput[];
  calculationTemplate?: CalculationTemplate | null;
  targetKind?: TargetKind | null;
  rangeMinGoal?: number | null;
  rangeMaxGoal?: number | null;
  subjectType?: SubjectType | null;
  subjectGoals?: SubjectGoal[];
  subjects?: SubjectSelection[];
  groupGoal?: GroupGoal | null;
  resultSemantics?: string | null;
  evaluationTypeCode?: string | null;
  comparisonDirection?: "INCREASE" | "REDUCTION" | null;
  calculationPattern?: string | null;
  measurementUnit: string;
  dataSource: string;
  ranges: TrafficLightRanges;
  isActive: boolean;
  effectiveFrom?: string;
  changeReason?: string;
};

export type KpiConfigLookups = {
  measurementUnits: Array<{ id: string; code: string; name: string; symbol: string; isPercentage: boolean }>;
  inputFrequencies: Array<{ id: string; code: string; name: string; monthsPerPeriod: number; periodsPerYear: number | null }>;
  dataSources: Array<{ id: string; code: string; name: string; sourceType: string }>;
  subjectCatalogs: Array<{ id: string; catalogId: string; subjectType: SubjectType; code: string; name: string }>;
};
