import { beforeEach, describe, expect, it, vi } from "vitest";
const tx=vi.hoisted(()=>({monitoringPeriod:{findUnique:vi.fn(),aggregate:vi.fn(),create:vi.fn(),findUniqueOrThrow:vi.fn()},monitoringPeriodStatus:{findUnique:vi.fn()},monitoringPeriodScorecard:{create:vi.fn()},monitoringPeriodInput:{create:vi.fn()},monitoringPeriodScorecardLink:{create:vi.fn()}}));
const db=vi.hoisted(()=>({monitoringPeriod:{findUnique:vi.fn()},$transaction:vi.fn()}));
const poolClient=vi.hoisted(()=>({context:vi.fn()}));
const scorecardsClient=vi.hoisted(()=>({materialization:vi.fn()}));
vi.mock("../config/prisma.js",()=>({prisma:db}));vi.mock("../clients/kpi-pool.client.js",()=>({kpiPoolClient:poolClient}));vi.mock("../clients/scorecards.client.js",()=>({scorecardsClient}));
import { monitoringPeriodService } from "../services/monitoring-period.service.js";
const pool={id:"9",poolCode:"OPS",poolName:"Operations",status:"ACTIVE",inputFrequency:{id:"1",code:"MONTHLY"},companies:[]};
const period={poolPeriodId:"101",poolCompositionId:"201",periodKey:"2026-08",start:"2026-08-01",end:"2026-08-31",workflowStatus:"FINALIZED"};
const snapshot={contractVersion:"FrozenEffectiveKpiSettingsV1",kpiConfigurationId:"501",kpiConfigurationRevisionId:"502",configCode:"KPC-1",kpiDefinitionId:"601",kpiCode:"KPI-1",kpiName:"Quality",objective:null,goal:"90",evaluationScope:"OVERALL",subjectType:null,subjectGoals:[],groupGoal:null,goalUnit:{id:"3",code:"PERCENT",name:"Percent",symbol:"%"},evaluationType:{id:"2",code:"GREATER_IS_BETTER",name:"Greater"},resultSemantics:"ABSOLUTE_VALUE",scoringMethod:"PROPORTIONAL",scoringRuleConfig:{floorPercent:0,capPercent:100},scoringRuleConfigVersion:1,negativeResultPolicy:"DISALLOW",scoringApprovalStatus:"APPROVED",measurementUnit:{id:"3",code:"PERCENT",name:"Percent",symbol:"%"},dataSource:{id:"4",code:"EMS",name:"EMS"},thresholds:[],executability:{capabilityVersion:"KPI_EXECUTION_V1",status:"EXECUTABLE",executable:true,reasons:[]}};
const projection=(settings:any=snapshot)=>({poolId:"9",poolInputPeriodId:"101",poolCompositionId:"201",periodKey:"2026-08",periodStart:period.start,periodEnd:period.end,readiness:"READY",reason:null,applicableScorecardCount:1,finalizedScorecardCount:1,scorecards:[{scorecardId:"11",scorecardCode:"SC-11",scorecardName:"Operations",lifecycle:"ACTIVE",compositionStatus:"FINALIZED",scorecardPeriodCompositionId:"301",departments:[],directKpiAssignments:[{scorecardKpiAssignmentId:"401",kpiConfigurationId:"501",kpiConfigurationRevisionId:"502",kpiDefinitionId:"601",poolMembershipExternalId:"701",effectiveSettings:settings,settingsProvenance:{GOAL:"GLOBAL_CONFIGURATION"},weightPercent:"100.0000",displayOrder:1}],linkedScorecards:[]}]});
const finalRow={id:1n,kpiPoolExternalId:9n,poolInputPeriodExternalId:101n,poolPeriodCompositionExternalId:201n,periodKey:"2026-08",periodStart:new Date("2026-08-01"),periodEnd:new Date("2026-08-31"),periodLabel:"August 2026",status:{code:"DRAFT"},scorecards:[],inputs:[]};
beforeEach(()=>{vi.clearAllMocks();db.monitoringPeriod.findUnique.mockResolvedValue(null);poolClient.context.mockResolvedValue({pool,period});scorecardsClient.materialization.mockResolvedValue(projection());tx.monitoringPeriod.findUnique.mockResolvedValue(null);tx.monitoringPeriodStatus.findUnique.mockResolvedValue({id:1n});tx.monitoringPeriod.aggregate.mockResolvedValue({_max:{sequenceNo:null}});tx.monitoringPeriod.create.mockResolvedValue({id:1n});tx.monitoringPeriodScorecard.create.mockResolvedValue({id:2n});tx.monitoringPeriodInput.create.mockResolvedValue({id:3n});tx.monitoringPeriod.findUniqueOrThrow.mockResolvedValue(finalRow);db.$transaction.mockImplementation((cb:any)=>cb(tx));});
describe("Monitoring materialization frozen settings",()=>{
 it("materializes each entity's Result Unit instead of the global unit",async()=>{
  const usd={id:"5",code:"USD",name:"Dollars",symbol:"USD"},mxn={id:"6",code:"MXN",name:"Pesos",symbol:"MXN"};
  scorecardsClient.materialization.mockResolvedValue(projection({...snapshot,evaluationScope:"BY_SUBJECT",evaluationWeightsVersion:"EXPLICIT_ENTITY_V1",subjectType:"COMPANY",subjectGoals:[usd,mxn].map((unit,i)=>({subjectExternalId:String(i),subjectCode:null,subjectLabel:String(i),goal:"100",weight:"50",goalUnit:unit,resultUnit:unit}))}));
  await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);
  expect(tx.monitoringPeriodInput.create.mock.calls.map(([args])=>args.data.measurementUnitCodeSnapshot)).toEqual(["USD","MXN"]);
  expect(tx.monitoringPeriodInput.create.mock.calls[1]![0].data.effectiveSettingsSnapshot.subjectGoals[1].goalUnit).toEqual(mxn);
 });
 it("blocks unmaterialized legacy entity snapshots without inferring weights",async()=>{scorecardsClient.materialization.mockResolvedValue(projection({...snapshot,evaluationScope:"BY_SUBJECT",subjectGoals:[{subjectExternalId:"A",subjectCode:"A",subjectLabel:"A",goal:"1"}]}));await expect(monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).rejects.toMatchObject({code:"FROZEN_ENTITY_WEIGHTS_MISSING"});expect(tx.monitoringPeriodInput.create).not.toHaveBeenCalled();});
 it("leaves already materialized legacy periods untouched",async()=>{db.monitoringPeriod.findUnique.mockResolvedValue(finalRow);await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);expect(scorecardsClient.materialization).not.toHaveBeenCalled();expect(db.$transaction).not.toHaveBeenCalled();});
 it("uses the Scorecard snapshot",async()=>{await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);expect(tx.monitoringPeriodInput.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({kpiConfigurationRevisionExternalId:502n,scoringApprovalStatusSnapshot:"APPROVED"})}));});
 it("creates exactly one input per frozen entity and never invents a Group Result",async()=>{scorecardsClient.materialization.mockResolvedValue(projection({...snapshot,evaluationScope:"BY_SUBJECT",evaluationWeightsVersion:"EXPLICIT_ENTITY_V1",subjectType:"COMPANY",goalUnit:{id:"5",code:"USD",name:"US Dollars",symbol:"USD"},subjectGoals:[{subjectExternalId:"10",subjectCode:"JAC",subjectLabel:"Jacky",goal:"0",weight:"65.1250"},{subjectExternalId:"11",subjectCode:"NAN",subjectLabel:"Nancy",goal:"60000",weight:"34.8750"}],groupGoal:{value:"140000",unit:"USD",label:"Group Goal"}}));await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);expect(tx.monitoringPeriodInput.create).toHaveBeenCalledTimes(2);expect(tx.monitoringPeriodInput.create.mock.calls.map(call => call[0].data.weightPercentSnapshot.toFixed(4))).toEqual(["65.1250","34.8750"]);expect(tx.monitoringPeriodInput.create).toHaveBeenNthCalledWith(1,expect.objectContaining({data:expect.objectContaining({evaluationKindSnapshot:"ENTITY",subjectLabelSnapshot:"Jacky",goalTextSnapshot:"0",goalValueSnapshot:expect.anything(),measurementUnitSymbolSnapshot:"%"})}));expect(tx.monitoringPeriodInput.create).not.toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({evaluationKindSnapshot:"GROUP"})}));});
 it("rejects an incomplete frozen snapshot instead of reinterpreting it",async()=>{scorecardsClient.materialization.mockResolvedValue(projection({...snapshot,scoringApprovalStatus:"BLOCKED",scoringMethod:null}));await expect(monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).rejects.toMatchObject({code:"FROZEN_KPI_SETTINGS_INVALID"});expect(tx.monitoringPeriodInput.create).not.toHaveBeenCalled();});
 it("is idempotent",async()=>{db.monitoringPeriod.findUnique.mockResolvedValue(finalRow);expect((await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).created).toBe(false);expect(poolClient.context).not.toHaveBeenCalled();});
 it("rejects incomplete Scorecards",async()=>{scorecardsClient.materialization.mockResolvedValue({...projection(),readiness:"NOT_READY",reason:"SCORECARD_COMPOSITIONS_INCOMPLETE",finalizedScorecardCount:0});await expect(monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).rejects.toMatchObject({code:"SCORECARDS_NOT_READY"});});
});
