import { beforeEach, describe, expect, it, vi } from "vitest";
const tx=vi.hoisted(()=>({monitoringPeriod:{findUnique:vi.fn(),aggregate:vi.fn(),create:vi.fn(),findUniqueOrThrow:vi.fn()},monitoringPeriodStatus:{findUnique:vi.fn()},monitoringPeriodScorecard:{create:vi.fn()},monitoringPeriodInput:{create:vi.fn()},monitoringPeriodScorecardLink:{create:vi.fn()}}));
const db=vi.hoisted(()=>({monitoringPeriod:{findUnique:vi.fn()},$transaction:vi.fn()}));
const poolClient=vi.hoisted(()=>({context:vi.fn()}));
const scorecardsClient=vi.hoisted(()=>({materialization:vi.fn()}));
vi.mock("../config/prisma.js",()=>({prisma:db}));vi.mock("../clients/kpi-pool.client.js",()=>({kpiPoolClient:poolClient}));vi.mock("../clients/scorecards.client.js",()=>({scorecardsClient}));
import { monitoringPeriodService } from "../services/monitoring-period.service.js";
const pool={id:"9",poolCode:"OPS",poolName:"Operations",status:"ACTIVE",inputFrequency:{id:"1",code:"MONTHLY"},companies:[]};
const period={poolPeriodId:"101",poolCompositionId:"201",periodKey:"2026-08",start:"2026-08-01",end:"2026-08-31",workflowStatus:"FINALIZED"};
const snapshot={kpiConfigurationId:"501",kpiConfigurationRevisionId:"502",configCode:"KPC-1",kpiDefinitionId:"601",kpiCode:"KPI-1",kpiName:"Quality",objective:null,goal:"90",evaluationType:{id:"2",code:"GREATER_IS_BETTER",name:"Greater"},resultSemantics:"ABSOLUTE_VALUE",scoringMethod:"PROPORTIONAL",scoringRuleConfig:{floorPercent:0,capPercent:100},scoringRuleConfigVersion:1,negativeResultPolicy:"DISALLOW",scoringApprovalStatus:"APPROVED",measurementUnit:{id:"3",code:"PERCENT",name:"Percent",symbol:"%"},dataSource:{id:"4",code:"EMS",name:"EMS"},thresholds:[]};
const projection=(settings:any=snapshot)=>({poolId:"9",poolInputPeriodId:"101",poolCompositionId:"201",periodKey:"2026-08",periodStart:period.start,periodEnd:period.end,readiness:"READY",reason:null,applicableScorecardCount:1,finalizedScorecardCount:1,scorecards:[{scorecardId:"11",scorecardCode:"SC-11",scorecardName:"Operations",lifecycle:"ACTIVE",compositionStatus:"FINALIZED",scorecardPeriodCompositionId:"301",departments:[],directKpiAssignments:[{scorecardKpiAssignmentId:"401",kpiConfigurationId:"501",kpiConfigurationRevisionId:"502",kpiDefinitionId:"601",poolMembershipExternalId:"701",effectiveSettings:settings,settingsProvenance:{GOAL:"GLOBAL_CONFIGURATION"},weightPercent:"100.0000",displayOrder:1}],linkedScorecards:[]}]});
const finalRow={id:1n,kpiPoolExternalId:9n,poolInputPeriodExternalId:101n,poolPeriodCompositionExternalId:201n,periodKey:"2026-08",periodStart:new Date("2026-08-01"),periodEnd:new Date("2026-08-31"),periodLabel:"August 2026",status:{code:"DRAFT"},scorecards:[],inputs:[]};
beforeEach(()=>{vi.clearAllMocks();db.monitoringPeriod.findUnique.mockResolvedValue(null);poolClient.context.mockResolvedValue({pool,period});scorecardsClient.materialization.mockResolvedValue(projection());tx.monitoringPeriod.findUnique.mockResolvedValue(null);tx.monitoringPeriodStatus.findUnique.mockResolvedValue({id:1n});tx.monitoringPeriod.aggregate.mockResolvedValue({_max:{sequenceNo:null}});tx.monitoringPeriod.create.mockResolvedValue({id:1n});tx.monitoringPeriodScorecard.create.mockResolvedValue({id:2n});tx.monitoringPeriodInput.create.mockResolvedValue({id:3n});tx.monitoringPeriod.findUniqueOrThrow.mockResolvedValue(finalRow);db.$transaction.mockImplementation((cb:any)=>cb(tx));});
describe("Monitoring materialization frozen settings",()=>{
 it("uses the Scorecard snapshot",async()=>{await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);expect(tx.monitoringPeriodInput.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({kpiConfigurationRevisionExternalId:502n,scoringApprovalStatusSnapshot:"APPROVED"})}));});
 it("preserves BLOCKED scoring",async()=>{scorecardsClient.materialization.mockResolvedValue(projection({...snapshot,scoringApprovalStatus:"BLOCKED",scoringMethod:null,scoringRuleConfig:null,scoringRuleConfigVersion:null}));await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n);expect(tx.monitoringPeriodInput.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({scoringApprovalStatusSnapshot:"BLOCKED",scoringMethodCodeSnapshot:null})}));});
 it("is idempotent",async()=>{db.monitoringPeriod.findUnique.mockResolvedValue(finalRow);expect((await monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).created).toBe(false);expect(poolClient.context).not.toHaveBeenCalled();});
 it("rejects incomplete Scorecards",async()=>{scorecardsClient.materialization.mockResolvedValue({...projection(),readiness:"NOT_READY",reason:"SCORECARD_COMPOSITIONS_INCOMPLETE",finalizedScorecardCount:0});await expect(monitoringPeriodService.materialize({poolId:"9",poolInputPeriodId:"101"},7n)).rejects.toMatchObject({code:"SCORECARDS_NOT_READY"});});
});
