import {afterAll,beforeAll,describe,expect,it,vi} from "vitest";
const poolClient=vi.hoisted(()=>({context:vi.fn()}));
const scorecardsClient=vi.hoisted(()=>({materialization:vi.fn()}));
vi.mock("../clients/kpi-pool.client.js",()=>({kpiPoolClient:poolClient}));
vi.mock("../clients/scorecards.client.js",()=>({scorecardsClient}));
import {prisma} from "../config/prisma.js";
import {monitoringPeriodService} from "../services/monitoring-period.service.js";

const run=process.env.RUN_MONITORING_MATERIALIZATION_SMOKE==="true"?describe:describe.skip;
const poolId=991100n;
const thresholds=["RED","YELLOW","GREEN"].map((code,index)=>({trafficLightLevelId:String(8100+index),code,name:code,rangeMinPercent:"0",rangeMaxPercent:"100",includesMin:true,includesMax:true,displayOrder:index+1}));
const base={contractVersion:"FrozenEffectiveKpiSettingsV1",kpiConfigurationRevisionId:"7002",kpiDefinitionId:"7003",objective:null,evaluationType:{id:"7004",code:"GREATER_IS_BETTER",name:"Greater is better"},resultSemantics:"ABSOLUTE_VALUE",scoringMethod:"PROPORTIONAL",scoringRuleConfig:{floorPercent:0,capPercent:100},scoringRuleConfigVersion:1,negativeResultPolicy:"DISALLOW",scoringApprovalStatus:"APPROVED",measurementUnit:{id:"7005",code:"USD",name:"US Dollars",symbol:"USD"},goalUnit:{id:"7005",code:"USD",name:"US Dollars",symbol:"USD"},dataSource:{id:"7006",code:"EMS",name:"EMS"},thresholds,executability:{capabilityVersion:"KPI_EXECUTION_V1",status:"EXECUTABLE",executable:true,reasons:[]}} as const;
const pool={id:poolId.toString(),poolCode:"PHASE-A-SMOKE",poolName:"Phase A Smoke",status:"ACTIVE",inputFrequency:{id:"1",code:"MONTHLY"},companies:[]};
const projection=(inputPeriodId:string,periodKey:string,effectiveSettings:any)=>({poolId:poolId.toString(),poolInputPeriodId:inputPeriodId,poolCompositionId:inputPeriodId,periodKey,periodStart:`${periodKey}-01`,periodEnd:`${periodKey}-28`,readiness:"READY",reason:null,applicableScorecardCount:1,finalizedScorecardCount:1,scorecards:[{scorecardId:`${inputPeriodId}1`,scorecardCode:`SC-${periodKey}`,scorecardName:"Smoke Scorecard",lifecycle:"ACTIVE",compositionStatus:"FINALIZED",scorecardPeriodCompositionId:`${inputPeriodId}2`,departments:[],directKpiAssignments:[{scorecardKpiAssignmentId:`${inputPeriodId}3`,kpiConfigurationId:effectiveSettings.kpiConfigurationId,kpiConfigurationRevisionId:effectiveSettings.kpiConfigurationRevisionId,kpiDefinitionId:effectiveSettings.kpiDefinitionId,poolMembershipExternalId:`${inputPeriodId}4`,effectiveSettings,settingsProvenance:{GOAL:"GLOBAL_CONFIGURATION"},weightPercent:"100.0000",displayOrder:1}],linkedScorecards:[]} ]});
async function cleanup(){const periods=await prisma.monitoringPeriod.findMany({where:{kpiPoolExternalId:poolId},select:{id:true}});for(const period of periods){await prisma.monitoringPeriodInput.deleteMany({where:{monitoringPeriodId:period.id}});await prisma.monitoringPeriodScorecard.deleteMany({where:{monitoringPeriodId:period.id}});await prisma.monitoringPeriod.delete({where:{id:period.id}});}}

run("Phase A materialization against MySQL",()=>{
 beforeAll(async()=>{await cleanup();}); afterAll(async()=>{await cleanup();await prisma.$disconnect();});
 it("materializes one OVERALL evaluation for Ventas",async()=>{const inputPeriodId="991101",periodKey="2098-01";const settings={...base,kpiConfigurationId:"7101",configCode:"KPC-SMOKE-OVERALL",kpiCode:"KPI-SALES",kpiName:"Ventas",goal:"50000",evaluationScope:"OVERALL",subjectType:null,subjectGoals:[],groupGoal:null};poolClient.context.mockResolvedValue({pool,period:{poolPeriodId:inputPeriodId,poolCompositionId:inputPeriodId,periodKey,start:`${periodKey}-01`,end:`${periodKey}-28`,workflowStatus:"FINALIZED"}});scorecardsClient.materialization.mockResolvedValue(projection(inputPeriodId,periodKey,settings));await monitoringPeriodService.materialize({poolId:poolId.toString(),poolInputPeriodId:inputPeriodId},1n);const rows=await prisma.monitoringPeriodInput.findMany({where:{period:{kpiPoolExternalId:poolId,poolInputPeriodExternalId:BigInt(inputPeriodId)}}});expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({evaluationKindSnapshot:"OVERALL",goalTextSnapshot:"50000",subjectExternalIdSnapshot:null});});
 it("materializes exactly three frozen BY_ENTITY evaluations",async()=>{const inputPeriodId="991102",periodKey="2098-02";const subjectGoals=[{subjectExternalId:"FLEET-NEW",subjectCode:"FLEET-NEW",subjectLabel:"Flota Nueva",goal:"4500"},{subjectExternalId:"TRANEXPA",subjectCode:"TRANEXPA",subjectLabel:"TRANEXPA",goal:"4000"},{subjectExternalId:"IPH",subjectCode:"IPH",subjectLabel:"IPH",goal:"3800"}];const settings={...base,kpiConfigurationId:"7201",configCode:"KPC-SMOKE-ENTITY",kpiCode:"KPI-HEAD-PROD",kpiName:"Productividad cabezales",goal:null,evaluationScope:"BY_SUBJECT",subjectType:"COMPANY",subjectGoals,groupGoal:null};poolClient.context.mockResolvedValue({pool,period:{poolPeriodId:inputPeriodId,poolCompositionId:inputPeriodId,periodKey,start:`${periodKey}-01`,end:`${periodKey}-28`,workflowStatus:"FINALIZED"}});scorecardsClient.materialization.mockResolvedValue(projection(inputPeriodId,periodKey,settings));await monitoringPeriodService.materialize({poolId:poolId.toString(),poolInputPeriodId:inputPeriodId},1n);const rows=await prisma.monitoringPeriodInput.findMany({where:{period:{kpiPoolExternalId:poolId,poolInputPeriodExternalId:BigInt(inputPeriodId)}},orderBy:{displayOrder:"asc"}});expect(rows.map((row)=>[row.subjectLabelSnapshot,row.goalTextSnapshot,row.evaluationKindSnapshot])).toEqual([["Flota Nueva","4500","ENTITY"],["TRANEXPA","4000","ENTITY"],["IPH","3800","ENTITY"]]);});
});
