import { Router } from "express";
import { createScorecard, deactivateScorecard, eligiblePools, getScorecard, listScorecards, updateScorecard } from "../controllers/scorecard.controller.js";
import { addKpis, addLink, availableKpis, availableLinks, finalizeComposition, getComposition, listPeriods, poolUsageBatch, poolWorkflow, removeKpi, removeLink, updateWeights } from "../controllers/scorecard-composition.controller.js";
export const scorecardRouter = Router();
scorecardRouter.get("/eligible-pools", eligiblePools);
scorecardRouter.get("/pool-workflow", poolWorkflow);
scorecardRouter.post("/pool-workflow/batch", poolUsageBatch);
scorecardRouter.get("/", listScorecards);
scorecardRouter.post("/", createScorecard);
scorecardRouter.get("/:id/periods", listPeriods);
scorecardRouter.get("/:id/periods/:periodKey/composition", getComposition);
scorecardRouter.get("/:id/periods/:periodKey/available-kpis", availableKpis);
scorecardRouter.post("/:id/periods/:periodKey/kpis", addKpis);
scorecardRouter.delete("/:id/periods/:periodKey/kpis/:configurationId", removeKpi);
scorecardRouter.patch("/:id/periods/:periodKey/weights", updateWeights);
scorecardRouter.get("/:id/periods/:periodKey/linked-scorecards", availableLinks);
scorecardRouter.post("/:id/periods/:periodKey/linked-scorecards", addLink);
scorecardRouter.delete("/:id/periods/:periodKey/linked-scorecards/:linkedScorecardId", removeLink);
scorecardRouter.post("/:id/periods/:periodKey/finalize", finalizeComposition);
scorecardRouter.get("/:id", getScorecard);
scorecardRouter.patch("/:id", updateScorecard);
scorecardRouter.patch("/:id/deactivate", deactivateScorecard);
